// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#ifndef INCLUDE_System_Xml_XPath
#define INCLUDE_System_Xml_XPath

#ifdef __cplusplus
extern "C" {
#endif

typedef const void* _Nonnull SG_HNDL_NONNULL;
typedef const void* _Nullable SG_HNDL_NULLABLE;
typedef const void* _Nonnull TYP;
typedef uint64_t GVAL;

TYP System_Xml_XPath_XPathDocument_get_type_handle(void);

SG_HNDL_NONNULL System_Xml_XPath_XPathDocument_ctor_0__1__Stream(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL stream);

SG_HNDL_NONNULL System_Xml_XPath_XPathDocument_ctor_0__1__TextReader(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL textReader);

SG_HNDL_NONNULL System_Xml_XPath_XPathDocument_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL uri);

SG_HNDL_NONNULL System_Xml_XPath_XPathDocument_ctor_0__2__String_XmlSpace(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL uri, int32_t space);

SG_HNDL_NONNULL System_Xml_XPath_XPathDocument_ctor_0__1__XmlReader(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL reader);

SG_HNDL_NONNULL System_Xml_XPath_XPathDocument_ctor_0__2__XmlReader_XmlSpace(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL reader, int32_t space);

SG_HNDL_NONNULL System_Xml_XPath_XPathDocument_XPathNavigator__CreateNavigator_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Xml_XPath_XPathDocument_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Xml_XPath_XPathException_get_type_handle(void);

SG_HNDL_NONNULL System_Xml_XPath_XPathException_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Xml_XPath_XPathException_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message);

SG_HNDL_NONNULL System_Xml_XPath_XPathException_ctor_0__2__String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE innerException);

void System_Xml_XPath_XPathException_void__GetObjectData_0__2__SerializationInfo_StreamingContext(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL info, SG_HNDL_NONNULL context);

SG_HNDL_NONNULL System_Xml_XPath_XPathException_String__get_Message_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Xml_XPath_XPathException_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);


#ifdef __cplusplus
}
#endif

#endif // INCLUDE_System_Xml_XPath

