// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#ifndef INCLUDE_System_Threading
#define INCLUDE_System_Threading

#ifdef __cplusplus
extern "C" {
#endif

typedef const void* _Nonnull SG_HNDL_NONNULL;
typedef const void* _Nullable SG_HNDL_NULLABLE;
typedef const void* _Nonnull TYP;
typedef uint64_t GVAL;

TYP System_Threading_AbandonedMutexException_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_AbandonedMutexException_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_AbandonedMutexException_ctor_0__2__i32_WaitHandle(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t location, SG_HNDL_NULLABLE handle);

SG_HNDL_NONNULL System_Threading_AbandonedMutexException_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message);

SG_HNDL_NONNULL System_Threading_AbandonedMutexException_ctor_0__2__String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE inner);

SG_HNDL_NONNULL System_Threading_AbandonedMutexException_ctor_0__4__String_Exception_i32_WaitHandle(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE inner, int32_t location, SG_HNDL_NULLABLE handle);

SG_HNDL_NONNULL System_Threading_AbandonedMutexException_ctor_0__3__String_i32_WaitHandle(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, int32_t location, SG_HNDL_NULLABLE handle);

SG_HNDL_NULLABLE System_Threading_AbandonedMutexException_Mutex__get_Mutex_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_AbandonedMutexException_i32__get_MutexIndex_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_AbandonedMutexException_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_AsyncFlowControl_get_type_handle(void);

void System_Threading_AsyncFlowControl_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_AsyncFlowControl_bool__Equals_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE obj);

int32_t System_Threading_AsyncFlowControl_bool__Equals_0__1__AsyncFlowControl(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL obj);

int32_t System_Threading_AsyncFlowControl_i32__GetHashCode_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_AsyncFlowControl_bool__op_Equality_0__2__AsyncFlowControl_AsyncFlowControl(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL a, SG_HNDL_NONNULL b);

int32_t System_Threading_AsyncFlowControl_bool__op_Inequality_0__2__AsyncFlowControl_AsyncFlowControl(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL a, SG_HNDL_NONNULL b);

void System_Threading_AsyncFlowControl_void__Undo_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_AsyncFlowControl_implicit_ctor(void);

TYP System_Threading_AsyncLocalValueChangedArgs_1_get_type_handle(TYP T);

GVAL System_Threading_AsyncLocalValueChangedArgs_1_T__get_CurrentValue_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL specialize_System_Threading_AsyncLocalValueChangedArgs_1_T__get_CurrentValue_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_AsyncLocalValueChangedArgs_1_T__get_CurrentValue_0__0(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

GVAL System_Threading_AsyncLocalValueChangedArgs_1_T__get_PreviousValue_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL specialize_System_Threading_AsyncLocalValueChangedArgs_1_T__get_PreviousValue_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_AsyncLocalValueChangedArgs_1_T__get_PreviousValue_0__0(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_AsyncLocalValueChangedArgs_1_bool__get_ThreadContextChanged_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL specialize_System_Threading_AsyncLocalValueChangedArgs_1_bool__get_ThreadContextChanged_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

int32_t invoke_System_Threading_AsyncLocalValueChangedArgs_1_bool__get_ThreadContextChanged_0__0(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_AsyncLocalValueChangedArgs_1_implicit_ctor(TYP T);

TYP System_Threading_AsyncLocal_1_get_type_handle(TYP T);

SG_HNDL_NONNULL System_Threading_AsyncLocal_1_ctor_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_AsyncLocal_1_ctor_0__1__System_Action_System_Threading_System_Threading_AsyncLocalValueChangedArgs_T__(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE valueChangedHandler);

GVAL System_Threading_AsyncLocal_1_T__get_Value_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL specialize_System_Threading_AsyncLocal_1_T__get_Value_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_AsyncLocal_1_T__get_Value_0__0(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_AsyncLocal_1_void__set_Value_0__1__T(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, GVAL value);

SG_HNDL_NONNULL specialize_System_Threading_AsyncLocal_1_void__set_Value_0__1__T(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

void invoke_System_Threading_AsyncLocal_1_void__set_Value_0__1__T(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, GVAL value);

SG_HNDL_NONNULL System_Threading_AsyncLocal_1_cast(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_AutoResetEvent_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_AutoResetEvent_ctor_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialState);

SG_HNDL_NONNULL System_Threading_AutoResetEvent_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_Barrier_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_Barrier_ctor_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t participantCount);

SG_HNDL_NONNULL System_Threading_Barrier_ctor_0__2__i32_System_Action_System_Threading_Barrier_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t participantCount, SG_HNDL_NULLABLE postPhaseAction);

int64_t System_Threading_Barrier_i64__AddParticipant_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int64_t System_Threading_Barrier_i64__AddParticipants_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t participantCount);

void System_Threading_Barrier_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_Barrier_void__RemoveParticipant_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_Barrier_void__RemoveParticipants_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t participantCount);

void System_Threading_Barrier_void__SignalAndWait_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_Barrier_bool__SignalAndWait_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

int32_t System_Threading_Barrier_bool__SignalAndWait_0__2__i32_CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout, SG_HNDL_NONNULL cancellationToken);

void System_Threading_Barrier_void__SignalAndWait_0__1__CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL cancellationToken);

int32_t System_Threading_Barrier_bool__SignalAndWait_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

int32_t System_Threading_Barrier_bool__SignalAndWait_0__2__TimeSpan_CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout, SG_HNDL_NONNULL cancellationToken);

int64_t System_Threading_Barrier_i64__get_CurrentPhaseNumber_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_Barrier_i32__get_ParticipantCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_Barrier_i32__get_ParticipantsRemaining_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_Barrier_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_BarrierPostPhaseException_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_BarrierPostPhaseException_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_BarrierPostPhaseException_ctor_0__1__Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE innerException);

SG_HNDL_NONNULL System_Threading_BarrierPostPhaseException_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message);

SG_HNDL_NONNULL System_Threading_BarrierPostPhaseException_ctor_0__2__String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE innerException);

SG_HNDL_NONNULL System_Threading_BarrierPostPhaseException_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_ContextCallback_get_type_handle(void);

void System_Threading_ContextCallback_void__Invoke_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE state);

SG_HNDL_NULLABLE System_Threading_ContextCallback_IAsyncResult__BeginInvoke_0__3__Object_AsyncCallback_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE state, SG_HNDL_NULLABLE callback, SG_HNDL_NULLABLE object_);

void System_Threading_ContextCallback_void__EndInvoke_0__1__IAsyncResult(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE result);

SG_HNDL_NONNULL System_Threading_ContextCallback_create(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nonnull  __cb)(const void* _Nonnull __pdata, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE state), const void* _Nonnull __pdata, void (* _Nullable __deinit)(const void* _Nonnull __pdata));

TYP System_Threading_CountdownEvent_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_CountdownEvent_ctor_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialCount);

void System_Threading_CountdownEvent_void__AddCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_CountdownEvent_void__AddCount_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t signalCount);

void System_Threading_CountdownEvent_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_CountdownEvent_void__Reset_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_CountdownEvent_void__Reset_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t count);

int32_t System_Threading_CountdownEvent_bool__Signal_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_CountdownEvent_bool__Signal_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t signalCount);

int32_t System_Threading_CountdownEvent_bool__TryAddCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_CountdownEvent_bool__TryAddCount_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t signalCount);

void System_Threading_CountdownEvent_void__Wait_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_CountdownEvent_bool__Wait_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

int32_t System_Threading_CountdownEvent_bool__Wait_0__2__i32_CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout, SG_HNDL_NONNULL cancellationToken);

void System_Threading_CountdownEvent_void__Wait_0__1__CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL cancellationToken);

int32_t System_Threading_CountdownEvent_bool__Wait_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

int32_t System_Threading_CountdownEvent_bool__Wait_0__2__TimeSpan_CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout, SG_HNDL_NONNULL cancellationToken);

int32_t System_Threading_CountdownEvent_i32__get_CurrentCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_CountdownEvent_i32__get_InitialCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_CountdownEvent_bool__get_IsSet_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_CountdownEvent_WaitHandle__get_WaitHandle_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_CountdownEvent_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_EventResetMode_get_type_handle(void);

int32_t System_Threading_EventResetMode_get_AutoReset(void);

int32_t System_Threading_EventResetMode_get_ManualReset(void);

TYP System_Threading_EventWaitHandle_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_EventWaitHandle_ctor_0__2__bool_EventResetMode(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialState, int32_t mode);

SG_HNDL_NONNULL System_Threading_EventWaitHandle_ctor_0__3__bool_EventResetMode_String(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialState, int32_t mode, SG_HNDL_NULLABLE name);

SG_HNDL_NONNULL System_Threading_EventWaitHandle_ctor_0__4__bool_EventResetMode_String_outbool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialState, int32_t mode, SG_HNDL_NULLABLE name, int32_t* _Nonnull __createdNew_out_ptr);

SG_HNDL_NONNULL System_Threading_EventWaitHandle_EventWaitHandle__OpenExisting_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL name);

int32_t System_Threading_EventWaitHandle_bool__Reset_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_EventWaitHandle_bool__Set_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_EventWaitHandle_bool__TryOpenExisting_0__2__String_outEventWaitHandle(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE* _Nonnull __result_out_ptr);

SG_HNDL_NONNULL System_Threading_EventWaitHandle_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_ExecutionContext_get_type_handle(void);

SG_HNDL_NULLABLE System_Threading_ExecutionContext_ExecutionContext__Capture_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_ExecutionContext_ExecutionContext__CreateCopy_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ExecutionContext_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ExecutionContext_void__GetObjectData_0__2__SerializationInfo_StreamingContext(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL info, SG_HNDL_NONNULL context);

int32_t System_Threading_ExecutionContext_bool__IsFlowSuppressed_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

void System_Threading_ExecutionContext_void__Restore_0__1__ExecutionContext(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL executionContext);

void System_Threading_ExecutionContext_void__RestoreFlow_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

void System_Threading_ExecutionContext_void__Run_0__3__ExecutionContext_ContextCallback_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL executionContext, SG_HNDL_NONNULL callback, SG_HNDL_NULLABLE state);

SG_HNDL_NONNULL System_Threading_ExecutionContext_AsyncFlowControl__SuppressFlow_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_ExecutionContext_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_HostExecutionContext_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_HostExecutionContext_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_HostExecutionContext_ctor_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE state);

SG_HNDL_NONNULL System_Threading_HostExecutionContext_HostExecutionContext__CreateCopy_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_HostExecutionContext_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_HostExecutionContext_void__Dispose_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t disposing);

SG_HNDL_NONNULL System_Threading_HostExecutionContext_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_HostExecutionContextManager_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_HostExecutionContextManager_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NULLABLE System_Threading_HostExecutionContextManager_HostExecutionContext__Capture_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_HostExecutionContextManager_void__Revert_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL previousState);

SG_HNDL_NONNULL System_Threading_HostExecutionContextManager_Object__SetHostExecutionContext_0__1__HostExecutionContext(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL hostExecutionContext);

SG_HNDL_NONNULL System_Threading_HostExecutionContextManager_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

int32_t System_Threading_Interlocked_i32__Add_0__2__refi32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location1_ref_ptr, int32_t value);

int64_t System_Threading_Interlocked_i64__Add_0__2__refi64_i64(SG_HNDL_NULLABLE * _Nonnull __thrown, int64_t* _Nonnull __location1_ref_ptr, int64_t value);

uint32_t System_Threading_Interlocked_u32__Add_0__2__refu32_u32(SG_HNDL_NULLABLE * _Nonnull __thrown, uint32_t* _Nonnull __location1_ref_ptr, uint32_t value);

uint64_t System_Threading_Interlocked_u64__Add_0__2__refu64_u64(SG_HNDL_NULLABLE * _Nonnull __thrown, uint64_t* _Nonnull __location1_ref_ptr, uint64_t value);

int32_t System_Threading_Interlocked_i32__And_0__2__refi32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location1_ref_ptr, int32_t value);

int64_t System_Threading_Interlocked_i64__And_0__2__refi64_i64(SG_HNDL_NULLABLE * _Nonnull __thrown, int64_t* _Nonnull __location1_ref_ptr, int64_t value);

uint32_t System_Threading_Interlocked_u32__And_0__2__refu32_u32(SG_HNDL_NULLABLE * _Nonnull __thrown, uint32_t* _Nonnull __location1_ref_ptr, uint32_t value);

uint64_t System_Threading_Interlocked_u64__And_0__2__refu64_u64(SG_HNDL_NULLABLE * _Nonnull __thrown, uint64_t* _Nonnull __location1_ref_ptr, uint64_t value);

double System_Threading_Interlocked_f64__CompareExchange_0__3__reff64_f64_f64(SG_HNDL_NULLABLE * _Nonnull __thrown, double* _Nonnull __location1_ref_ptr, double value, double comparand);

int32_t System_Threading_Interlocked_i32__CompareExchange_0__3__refi32_i32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location1_ref_ptr, int32_t value, int32_t comparand);

int64_t System_Threading_Interlocked_i64__CompareExchange_0__3__refi64_i64_i64(SG_HNDL_NULLABLE * _Nonnull __thrown, int64_t* _Nonnull __location1_ref_ptr, int64_t value, int64_t comparand);

intptr_t System_Threading_Interlocked_IntPtr__CompareExchange_0__3__refIntPtr_IntPtr_IntPtr(SG_HNDL_NULLABLE * _Nonnull __thrown, intptr_t* _Nonnull __location1_ref_ptr, intptr_t value, intptr_t comparand);

SG_HNDL_NULLABLE System_Threading_Interlocked_Object__CompareExchange_0__3__refObject_Object_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE* _Nonnull __location1_ref_ptr, SG_HNDL_NULLABLE value, SG_HNDL_NULLABLE comparand);

float System_Threading_Interlocked_f32__CompareExchange_0__3__reff32_f32_f32(SG_HNDL_NULLABLE * _Nonnull __thrown, float* _Nonnull __location1_ref_ptr, float value, float comparand);

uint32_t System_Threading_Interlocked_u32__CompareExchange_0__3__refu32_u32_u32(SG_HNDL_NULLABLE * _Nonnull __thrown, uint32_t* _Nonnull __location1_ref_ptr, uint32_t value, uint32_t comparand);

uint64_t System_Threading_Interlocked_u64__CompareExchange_0__3__refu64_u64_u64(SG_HNDL_NULLABLE * _Nonnull __thrown, uint64_t* _Nonnull __location1_ref_ptr, uint64_t value, uint64_t comparand);

GVAL System_Threading_Interlocked_UT__CompareExchange_1__3__refUT_UT_UT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __location1_ref_ptr, GVAL value, GVAL comparand);

SG_HNDL_NONNULL specialize_System_Threading_Interlocked_UT__CompareExchange_1__3__refUT_UT_UT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_Interlocked_UT__CompareExchange_1__3__refUT_UT_UT(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __location1_ref_ptr, GVAL value, GVAL comparand);

int32_t System_Threading_Interlocked_i32__Decrement_0__1__refi32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location_ref_ptr);

int64_t System_Threading_Interlocked_i64__Decrement_0__1__refi64(SG_HNDL_NULLABLE * _Nonnull __thrown, int64_t* _Nonnull __location_ref_ptr);

uint32_t System_Threading_Interlocked_u32__Decrement_0__1__refu32(SG_HNDL_NULLABLE * _Nonnull __thrown, uint32_t* _Nonnull __location_ref_ptr);

uint64_t System_Threading_Interlocked_u64__Decrement_0__1__refu64(SG_HNDL_NULLABLE * _Nonnull __thrown, uint64_t* _Nonnull __location_ref_ptr);

double System_Threading_Interlocked_f64__Exchange_0__2__reff64_f64(SG_HNDL_NULLABLE * _Nonnull __thrown, double* _Nonnull __location1_ref_ptr, double value);

int32_t System_Threading_Interlocked_i32__Exchange_0__2__refi32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location1_ref_ptr, int32_t value);

int64_t System_Threading_Interlocked_i64__Exchange_0__2__refi64_i64(SG_HNDL_NULLABLE * _Nonnull __thrown, int64_t* _Nonnull __location1_ref_ptr, int64_t value);

intptr_t System_Threading_Interlocked_IntPtr__Exchange_0__2__refIntPtr_IntPtr(SG_HNDL_NULLABLE * _Nonnull __thrown, intptr_t* _Nonnull __location1_ref_ptr, intptr_t value);

SG_HNDL_NULLABLE System_Threading_Interlocked_Object__Exchange_0__2__refObject_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE* _Nonnull __location1_ref_ptr, SG_HNDL_NULLABLE value);

float System_Threading_Interlocked_f32__Exchange_0__2__reff32_f32(SG_HNDL_NULLABLE * _Nonnull __thrown, float* _Nonnull __location1_ref_ptr, float value);

uint32_t System_Threading_Interlocked_u32__Exchange_0__2__refu32_u32(SG_HNDL_NULLABLE * _Nonnull __thrown, uint32_t* _Nonnull __location1_ref_ptr, uint32_t value);

uint64_t System_Threading_Interlocked_u64__Exchange_0__2__refu64_u64(SG_HNDL_NULLABLE * _Nonnull __thrown, uint64_t* _Nonnull __location1_ref_ptr, uint64_t value);

GVAL System_Threading_Interlocked_UT__Exchange_1__2__refUT_UT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __location1_ref_ptr, GVAL value);

SG_HNDL_NONNULL specialize_System_Threading_Interlocked_UT__Exchange_1__2__refUT_UT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_Interlocked_UT__Exchange_1__2__refUT_UT(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __location1_ref_ptr, GVAL value);

int32_t System_Threading_Interlocked_i32__Increment_0__1__refi32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location_ref_ptr);

int64_t System_Threading_Interlocked_i64__Increment_0__1__refi64(SG_HNDL_NULLABLE * _Nonnull __thrown, int64_t* _Nonnull __location_ref_ptr);

uint32_t System_Threading_Interlocked_u32__Increment_0__1__refu32(SG_HNDL_NULLABLE * _Nonnull __thrown, uint32_t* _Nonnull __location_ref_ptr);

uint64_t System_Threading_Interlocked_u64__Increment_0__1__refu64(SG_HNDL_NULLABLE * _Nonnull __thrown, uint64_t* _Nonnull __location_ref_ptr);

void System_Threading_Interlocked_void__MemoryBarrier_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

void System_Threading_Interlocked_void__MemoryBarrierProcessWide_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

int32_t System_Threading_Interlocked_i32__Or_0__2__refi32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location1_ref_ptr, int32_t value);

int64_t System_Threading_Interlocked_i64__Or_0__2__refi64_i64(SG_HNDL_NULLABLE * _Nonnull __thrown, int64_t* _Nonnull __location1_ref_ptr, int64_t value);

uint32_t System_Threading_Interlocked_u32__Or_0__2__refu32_u32(SG_HNDL_NULLABLE * _Nonnull __thrown, uint32_t* _Nonnull __location1_ref_ptr, uint32_t value);

uint64_t System_Threading_Interlocked_u64__Or_0__2__refu64_u64(SG_HNDL_NULLABLE * _Nonnull __thrown, uint64_t* _Nonnull __location1_ref_ptr, uint64_t value);

int64_t System_Threading_Interlocked_i64__Read_0__1__refi64(SG_HNDL_NULLABLE * _Nonnull __thrown, int64_t* _Nonnull __location_ref_ptr);

uint64_t System_Threading_Interlocked_u64__Read_0__1__refu64(SG_HNDL_NULLABLE * _Nonnull __thrown, uint64_t* _Nonnull __location_ref_ptr);

GVAL System_Threading_LazyInitializer_UT__EnsureInitialized_1__1__refUT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __target_ref_ptr);

SG_HNDL_NONNULL specialize_System_Threading_LazyInitializer_UT__EnsureInitialized_1__1__refUT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_LazyInitializer_UT__EnsureInitialized_1__1__refUT(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __target_ref_ptr);

GVAL System_Threading_LazyInitializer_UT__EnsureInitialized_1__3__refUT_refbool_refObject(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __target_ref_ptr, int32_t* _Nonnull __initialized_ref_ptr, SG_HNDL_NULLABLE* _Nonnull __syncLock_ref_ptr);

SG_HNDL_NONNULL specialize_System_Threading_LazyInitializer_UT__EnsureInitialized_1__3__refUT_refbool_refObject(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_LazyInitializer_UT__EnsureInitialized_1__3__refUT_refbool_refObject(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __target_ref_ptr, int32_t* _Nonnull __initialized_ref_ptr, SG_HNDL_NULLABLE* _Nonnull __syncLock_ref_ptr);

GVAL System_Threading_LazyInitializer_UT__EnsureInitialized_1__4__refUT_refbool_refObject_System_Func_UT_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __target_ref_ptr, int32_t* _Nonnull __initialized_ref_ptr, SG_HNDL_NULLABLE* _Nonnull __syncLock_ref_ptr, SG_HNDL_NONNULL valueFactory);

SG_HNDL_NONNULL specialize_System_Threading_LazyInitializer_UT__EnsureInitialized_1__4__refUT_refbool_refObject_System_Func_UT_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_LazyInitializer_UT__EnsureInitialized_1__4__refUT_refbool_refObject_System_Func_UT_(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __target_ref_ptr, int32_t* _Nonnull __initialized_ref_ptr, SG_HNDL_NULLABLE* _Nonnull __syncLock_ref_ptr, SG_HNDL_NONNULL valueFactory);

GVAL System_Threading_LazyInitializer_UT__EnsureInitialized_1__2__refUT_System_Func_UT_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __target_ref_ptr, SG_HNDL_NONNULL valueFactory);

SG_HNDL_NONNULL specialize_System_Threading_LazyInitializer_UT__EnsureInitialized_1__2__refUT_System_Func_UT_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_LazyInitializer_UT__EnsureInitialized_1__2__refUT_System_Func_UT_(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __target_ref_ptr, SG_HNDL_NONNULL valueFactory);

GVAL System_Threading_LazyInitializer_UT__EnsureInitialized_1__3__refUT_refObject_System_Func_UT_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __target_ref_ptr, SG_HNDL_NULLABLE* _Nonnull __syncLock_ref_ptr, SG_HNDL_NONNULL valueFactory);

SG_HNDL_NONNULL specialize_System_Threading_LazyInitializer_UT__EnsureInitialized_1__3__refUT_refObject_System_Func_UT_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_LazyInitializer_UT__EnsureInitialized_1__3__refUT_refObject_System_Func_UT_(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __target_ref_ptr, SG_HNDL_NULLABLE* _Nonnull __syncLock_ref_ptr, SG_HNDL_NONNULL valueFactory);

TYP System_Threading_LockCookie_get_type_handle(void);

int32_t System_Threading_LockCookie_bool__Equals_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE obj);

int32_t System_Threading_LockCookie_bool__Equals_0__1__LockCookie(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL obj);

int32_t System_Threading_LockCookie_i32__GetHashCode_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_LockCookie_bool__op_Equality_0__2__LockCookie_LockCookie(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL a, SG_HNDL_NONNULL b);

int32_t System_Threading_LockCookie_bool__op_Inequality_0__2__LockCookie_LockCookie(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL a, SG_HNDL_NONNULL b);

SG_HNDL_NONNULL System_Threading_LockCookie_implicit_ctor(void);

TYP System_Threading_LockRecursionException_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_LockRecursionException_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_LockRecursionException_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message);

SG_HNDL_NONNULL System_Threading_LockRecursionException_ctor_0__2__String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE innerException);

SG_HNDL_NONNULL System_Threading_LockRecursionException_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_LockRecursionPolicy_get_type_handle(void);

int32_t System_Threading_LockRecursionPolicy_get_NoRecursion(void);

int32_t System_Threading_LockRecursionPolicy_get_SupportsRecursion(void);

TYP System_Threading_ManualResetEvent_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_ManualResetEvent_ctor_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialState);

SG_HNDL_NONNULL System_Threading_ManualResetEvent_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_ManualResetEventSlim_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_ManualResetEventSlim_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_ManualResetEventSlim_ctor_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialState);

SG_HNDL_NONNULL System_Threading_ManualResetEventSlim_ctor_0__2__bool_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialState, int32_t spinCount);

void System_Threading_ManualResetEventSlim_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ManualResetEventSlim_void__Reset_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ManualResetEventSlim_void__Set_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ManualResetEventSlim_void__Wait_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ManualResetEventSlim_bool__Wait_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

int32_t System_Threading_ManualResetEventSlim_bool__Wait_0__2__i32_CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout, SG_HNDL_NONNULL cancellationToken);

void System_Threading_ManualResetEventSlim_void__Wait_0__1__CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL cancellationToken);

int32_t System_Threading_ManualResetEventSlim_bool__Wait_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

int32_t System_Threading_ManualResetEventSlim_bool__Wait_0__2__TimeSpan_CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout, SG_HNDL_NONNULL cancellationToken);

int32_t System_Threading_ManualResetEventSlim_bool__get_IsSet_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ManualResetEventSlim_i32__get_SpinCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_ManualResetEventSlim_WaitHandle__get_WaitHandle_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_ManualResetEventSlim_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

void System_Threading_Monitor_void__Enter_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj);

void System_Threading_Monitor_void__Enter_0__2__Object_refbool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj, int32_t* _Nonnull __lockTaken_ref_ptr);

void System_Threading_Monitor_void__Exit_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj);

int32_t System_Threading_Monitor_bool__IsEntered_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj);

void System_Threading_Monitor_void__Pulse_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj);

void System_Threading_Monitor_void__PulseAll_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj);

int32_t System_Threading_Monitor_bool__TryEnter_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj);

void System_Threading_Monitor_void__TryEnter_0__2__Object_refbool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj, int32_t* _Nonnull __lockTaken_ref_ptr);

int32_t System_Threading_Monitor_bool__TryEnter_0__2__Object_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj, int32_t millisecondsTimeout);

void System_Threading_Monitor_void__TryEnter_0__3__Object_i32_refbool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj, int32_t millisecondsTimeout, int32_t* _Nonnull __lockTaken_ref_ptr);

int32_t System_Threading_Monitor_bool__TryEnter_0__2__Object_TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj, SG_HNDL_NONNULL timeout);

void System_Threading_Monitor_void__TryEnter_0__3__Object_TimeSpan_refbool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj, SG_HNDL_NONNULL timeout, int32_t* _Nonnull __lockTaken_ref_ptr);

int32_t System_Threading_Monitor_bool__Wait_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj);

int32_t System_Threading_Monitor_bool__Wait_0__2__Object_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj, int32_t millisecondsTimeout);

int32_t System_Threading_Monitor_bool__Wait_0__3__Object_i32_bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj, int32_t millisecondsTimeout, int32_t exitContext);

int32_t System_Threading_Monitor_bool__Wait_0__2__Object_TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj, SG_HNDL_NONNULL timeout);

int32_t System_Threading_Monitor_bool__Wait_0__3__Object_TimeSpan_bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL obj, SG_HNDL_NONNULL timeout, int32_t exitContext);

int64_t System_Threading_Monitor_i64__get_LockContentionCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

TYP System_Threading_Mutex_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_Mutex_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_Mutex_ctor_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initiallyOwned);

SG_HNDL_NONNULL System_Threading_Mutex_ctor_0__2__bool_String(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initiallyOwned, SG_HNDL_NULLABLE name);

SG_HNDL_NONNULL System_Threading_Mutex_ctor_0__3__bool_String_outbool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initiallyOwned, SG_HNDL_NULLABLE name, int32_t* _Nonnull __createdNew_out_ptr);

SG_HNDL_NONNULL System_Threading_Mutex_Mutex__OpenExisting_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL name);

void System_Threading_Mutex_void__ReleaseMutex_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_Mutex_bool__TryOpenExisting_0__2__String_outMutex(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE* _Nonnull __result_out_ptr);

SG_HNDL_NONNULL System_Threading_Mutex_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_ReaderWriterLock_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_ReaderWriterLock_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

void System_Threading_ReaderWriterLock_void__AcquireReaderLock_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

void System_Threading_ReaderWriterLock_void__AcquireReaderLock_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

void System_Threading_ReaderWriterLock_void__AcquireWriterLock_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

void System_Threading_ReaderWriterLock_void__AcquireWriterLock_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

int32_t System_Threading_ReaderWriterLock_bool__AnyWritersSince_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t seqNum);

void System_Threading_ReaderWriterLock_void__DowngradeFromWriterLock_0__1__refLockCookie(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE* _Nonnull __lockCookie_ref_ptr);

SG_HNDL_NONNULL System_Threading_ReaderWriterLock_LockCookie__ReleaseLock_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ReaderWriterLock_void__ReleaseReaderLock_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ReaderWriterLock_void__ReleaseWriterLock_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ReaderWriterLock_void__RestoreLock_0__1__refLockCookie(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE* _Nonnull __lockCookie_ref_ptr);

SG_HNDL_NONNULL System_Threading_ReaderWriterLock_LockCookie__UpgradeToWriterLock_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

SG_HNDL_NONNULL System_Threading_ReaderWriterLock_LockCookie__UpgradeToWriterLock_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

int32_t System_Threading_ReaderWriterLock_bool__get_IsReaderLockHeld_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLock_bool__get_IsWriterLockHeld_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLock_i32__get_WriterSeqNum_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_ReaderWriterLock_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_ReaderWriterLockSlim_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_ReaderWriterLockSlim_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_ReaderWriterLockSlim_ctor_0__1__LockRecursionPolicy(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t recursionPolicy);

void System_Threading_ReaderWriterLockSlim_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ReaderWriterLockSlim_void__EnterReadLock_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ReaderWriterLockSlim_void__EnterUpgradeableReadLock_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ReaderWriterLockSlim_void__EnterWriteLock_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ReaderWriterLockSlim_void__ExitReadLock_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ReaderWriterLockSlim_void__ExitUpgradeableReadLock_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ReaderWriterLockSlim_void__ExitWriteLock_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_bool__TryEnterReadLock_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

int32_t System_Threading_ReaderWriterLockSlim_bool__TryEnterReadLock_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

int32_t System_Threading_ReaderWriterLockSlim_bool__TryEnterUpgradeableReadLock_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

int32_t System_Threading_ReaderWriterLockSlim_bool__TryEnterUpgradeableReadLock_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

int32_t System_Threading_ReaderWriterLockSlim_bool__TryEnterWriteLock_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

int32_t System_Threading_ReaderWriterLockSlim_bool__TryEnterWriteLock_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

int32_t System_Threading_ReaderWriterLockSlim_i32__get_CurrentReadCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_bool__get_IsReadLockHeld_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_bool__get_IsUpgradeableReadLockHeld_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_bool__get_IsWriteLockHeld_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_LockRecursionPolicy__get_RecursionPolicy_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_i32__get_RecursiveReadCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_i32__get_RecursiveUpgradeCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_i32__get_RecursiveWriteCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_i32__get_WaitingReadCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_i32__get_WaitingUpgradeCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ReaderWriterLockSlim_i32__get_WaitingWriteCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_ReaderWriterLockSlim_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_Semaphore_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_Semaphore_ctor_0__2__i32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialCount, int32_t maximumCount);

SG_HNDL_NONNULL System_Threading_Semaphore_ctor_0__3__i32_i32_String(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialCount, int32_t maximumCount, SG_HNDL_NULLABLE name);

SG_HNDL_NONNULL System_Threading_Semaphore_ctor_0__4__i32_i32_String_outbool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialCount, int32_t maximumCount, SG_HNDL_NULLABLE name, int32_t* _Nonnull __createdNew_out_ptr);

SG_HNDL_NONNULL System_Threading_Semaphore_Semaphore__OpenExisting_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL name);

int32_t System_Threading_Semaphore_i32__Release_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_Semaphore_i32__Release_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t releaseCount);

int32_t System_Threading_Semaphore_bool__TryOpenExisting_0__2__String_outSemaphore(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE* _Nonnull __result_out_ptr);

SG_HNDL_NONNULL System_Threading_Semaphore_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_SemaphoreFullException_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_SemaphoreFullException_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_SemaphoreFullException_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message);

SG_HNDL_NONNULL System_Threading_SemaphoreFullException_ctor_0__2__String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE innerException);

SG_HNDL_NONNULL System_Threading_SemaphoreFullException_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_SemaphoreSlim_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_SemaphoreSlim_ctor_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialCount);

SG_HNDL_NONNULL System_Threading_SemaphoreSlim_ctor_0__2__i32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialCount, int32_t maxCount);

void System_Threading_SemaphoreSlim_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_SemaphoreSlim_i32__Release_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_SemaphoreSlim_i32__Release_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t releaseCount);

void System_Threading_SemaphoreSlim_void__Wait_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_SemaphoreSlim_bool__Wait_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

int32_t System_Threading_SemaphoreSlim_bool__Wait_0__2__i32_CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout, SG_HNDL_NONNULL cancellationToken);

void System_Threading_SemaphoreSlim_void__Wait_0__1__CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL cancellationToken);

int32_t System_Threading_SemaphoreSlim_bool__Wait_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

int32_t System_Threading_SemaphoreSlim_bool__Wait_0__2__TimeSpan_CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout, SG_HNDL_NONNULL cancellationToken);

SG_HNDL_NONNULL System_Threading_SemaphoreSlim_Task__WaitAsync_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_SemaphoreSlim_System_Threading_Tasks_Task_bool___WaitAsync_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout);

SG_HNDL_NONNULL System_Threading_SemaphoreSlim_System_Threading_Tasks_Task_bool___WaitAsync_0__2__i32_CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout, SG_HNDL_NONNULL cancellationToken);

SG_HNDL_NONNULL System_Threading_SemaphoreSlim_Task__WaitAsync_0__1__CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL cancellationToken);

SG_HNDL_NONNULL System_Threading_SemaphoreSlim_System_Threading_Tasks_Task_bool___WaitAsync_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout);

SG_HNDL_NONNULL System_Threading_SemaphoreSlim_System_Threading_Tasks_Task_bool___WaitAsync_0__2__TimeSpan_CancellationToken(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout, SG_HNDL_NONNULL cancellationToken);

SG_HNDL_NONNULL System_Threading_SemaphoreSlim_WaitHandle__get_AvailableWaitHandle_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_SemaphoreSlim_i32__get_CurrentCount_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_SemaphoreSlim_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_SendOrPostCallback_get_type_handle(void);

void System_Threading_SendOrPostCallback_void__Invoke_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE state);

SG_HNDL_NULLABLE System_Threading_SendOrPostCallback_IAsyncResult__BeginInvoke_0__3__Object_AsyncCallback_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE state, SG_HNDL_NULLABLE callback, SG_HNDL_NULLABLE object_);

void System_Threading_SendOrPostCallback_void__EndInvoke_0__1__IAsyncResult(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE result);

SG_HNDL_NONNULL System_Threading_SendOrPostCallback_create(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nonnull  __cb)(const void* _Nonnull __pdata, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE state), const void* _Nonnull __pdata, void (* _Nullable __deinit)(const void* _Nonnull __pdata));

TYP System_Threading_SpinLock_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_SpinLock_ctor_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t enableThreadOwnerTracking);

void System_Threading_SpinLock_void__Enter_0__1__refbool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t* _Nonnull __lockTaken_ref_ptr);

void System_Threading_SpinLock_void__Exit_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_SpinLock_void__Exit_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t useMemoryBarrier);

void System_Threading_SpinLock_void__TryEnter_0__1__refbool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t* _Nonnull __lockTaken_ref_ptr);

void System_Threading_SpinLock_void__TryEnter_0__2__i32_refbool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t millisecondsTimeout, int32_t* _Nonnull __lockTaken_ref_ptr);

void System_Threading_SpinLock_void__TryEnter_0__2__TimeSpan_refbool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL timeout, int32_t* _Nonnull __lockTaken_ref_ptr);

int32_t System_Threading_SpinLock_bool__get_IsHeld_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_SpinLock_bool__get_IsHeldByCurrentThread_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_SpinLock_bool__get_IsThreadOwnerTrackingEnabled_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_SpinLock_implicit_ctor(void);

TYP System_Threading_SpinWait_get_type_handle(void);

void System_Threading_SpinWait_void__Reset_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_SpinWait_void__SpinOnce_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_SpinWait_void__SpinOnce_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t sleep1Threshold);

void System_Threading_SpinWait_void__SpinUntil_0__1__System_Func_bool_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL condition);

int32_t System_Threading_SpinWait_bool__SpinUntil_0__2__System_Func_bool__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL condition, int32_t millisecondsTimeout);

int32_t System_Threading_SpinWait_bool__SpinUntil_0__2__System_Func_bool__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL condition, SG_HNDL_NONNULL timeout);

int32_t System_Threading_SpinWait_i32__get_Count_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_SpinWait_bool__get_NextSpinWillYield_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_SpinWait_implicit_ctor(void);

TYP System_Threading_SynchronizationContext_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_SynchronizationContext_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_SynchronizationContext_SynchronizationContext__CreateCopy_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_SynchronizationContext_bool__IsWaitNotificationRequired_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_SynchronizationContext_void__OperationCompleted_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_SynchronizationContext_void__OperationStarted_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_SynchronizationContext_void__Post_0__2__SendOrPostCallback_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL d, SG_HNDL_NULLABLE state);

void System_Threading_SynchronizationContext_void__Send_0__2__SendOrPostCallback_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL d, SG_HNDL_NULLABLE state);

void System_Threading_SynchronizationContext_void__SetSynchronizationContext_0__1__SynchronizationContext(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE syncContext);

int32_t System_Threading_SynchronizationContext_i32__Wait_0__3__IntPtrArray_bool_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL waitHandles, int32_t waitAll, int32_t millisecondsTimeout);

SG_HNDL_NULLABLE System_Threading_SynchronizationContext_SynchronizationContext__get_Current_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_SynchronizationContext_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_SynchronizationLockException_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_SynchronizationLockException_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_SynchronizationLockException_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message);

SG_HNDL_NONNULL System_Threading_SynchronizationLockException_ctor_0__2__String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE innerException);

SG_HNDL_NONNULL System_Threading_SynchronizationLockException_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

TYP System_Threading_ThreadLocal_1_get_type_handle(TYP T);

SG_HNDL_NONNULL System_Threading_ThreadLocal_1_ctor_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_ThreadLocal_1_ctor_0__1__bool(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t trackAllValues);

SG_HNDL_NONNULL System_Threading_ThreadLocal_1_ctor_0__1__System_Func_T_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL valueFactory);

SG_HNDL_NONNULL System_Threading_ThreadLocal_1_ctor_0__2__System_Func_T__bool(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL valueFactory, int32_t trackAllValues);

void System_Threading_ThreadLocal_1_void__Dispose_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL specialize_System_Threading_ThreadLocal_1_void__Dispose_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

void invoke_System_Threading_ThreadLocal_1_void__Dispose_0__0(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NULLABLE System_Threading_ThreadLocal_1_String__ToString_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL specialize_System_Threading_ThreadLocal_1_String__ToString_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NULLABLE invoke_System_Threading_ThreadLocal_1_String__ToString_0__0(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

int32_t System_Threading_ThreadLocal_1_bool__get_IsValueCreated_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL specialize_System_Threading_ThreadLocal_1_bool__get_IsValueCreated_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

int32_t invoke_System_Threading_ThreadLocal_1_bool__get_IsValueCreated_0__0(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

GVAL System_Threading_ThreadLocal_1_T__get_Value_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL specialize_System_Threading_ThreadLocal_1_T__get_Value_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_ThreadLocal_1_T__get_Value_0__0(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

void System_Threading_ThreadLocal_1_void__set_Value_0__1__T(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, GVAL value);

SG_HNDL_NONNULL specialize_System_Threading_ThreadLocal_1_void__set_Value_0__1__T(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

void invoke_System_Threading_ThreadLocal_1_void__set_Value_0__1__T(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, GVAL value);

SG_HNDL_NONNULL System_Threading_ThreadLocal_1_System_Collections_Generic_IList_T___get_Values_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL specialize_System_Threading_ThreadLocal_1_System_Collections_Generic_IList_T___get_Values_0__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL invoke_System_Threading_ThreadLocal_1_System_Collections_Generic_IList_T___get_Values_0__0(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);

SG_HNDL_NONNULL System_Threading_ThreadLocal_1_cast(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);

int32_t System_Threading_Volatile_bool__Read_0__1__refbool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location_ref_ptr);

uint8_t System_Threading_Volatile_u8__Read_0__1__refu8(SG_HNDL_NULLABLE * _Nonnull __thrown, uint8_t* _Nonnull __location_ref_ptr);

double System_Threading_Volatile_f64__Read_0__1__reff64(SG_HNDL_NULLABLE * _Nonnull __thrown, double* _Nonnull __location_ref_ptr);

int16_t System_Threading_Volatile_i16__Read_0__1__refi16(SG_HNDL_NULLABLE * _Nonnull __thrown, int16_t* _Nonnull __location_ref_ptr);

int32_t System_Threading_Volatile_i32__Read_0__1__refi32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location_ref_ptr);

int64_t System_Threading_Volatile_i64__Read_0__1__refi64(SG_HNDL_NULLABLE * _Nonnull __thrown, int64_t* _Nonnull __location_ref_ptr);

intptr_t System_Threading_Volatile_IntPtr__Read_0__1__refIntPtr(SG_HNDL_NULLABLE * _Nonnull __thrown, intptr_t* _Nonnull __location_ref_ptr);

int8_t System_Threading_Volatile_i8__Read_0__1__refi8(SG_HNDL_NULLABLE * _Nonnull __thrown, int8_t* _Nonnull __location_ref_ptr);

float System_Threading_Volatile_f32__Read_0__1__reff32(SG_HNDL_NULLABLE * _Nonnull __thrown, float* _Nonnull __location_ref_ptr);

uint16_t System_Threading_Volatile_u16__Read_0__1__refu16(SG_HNDL_NULLABLE * _Nonnull __thrown, uint16_t* _Nonnull __location_ref_ptr);

uint32_t System_Threading_Volatile_u32__Read_0__1__refu32(SG_HNDL_NULLABLE * _Nonnull __thrown, uint32_t* _Nonnull __location_ref_ptr);

uint64_t System_Threading_Volatile_u64__Read_0__1__refu64(SG_HNDL_NULLABLE * _Nonnull __thrown, uint64_t* _Nonnull __location_ref_ptr);

SG_HNDL_NONNULL System_Threading_Volatile_UIntPtr__Read_0__1__refUIntPtr(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL* _Nonnull __location_ref_ptr);

GVAL System_Threading_Volatile_UT__Read_1__1__refUT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __location_ref_ptr);

SG_HNDL_NONNULL specialize_System_Threading_Volatile_UT__Read_1__1__refUT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

GVAL invoke_System_Threading_Volatile_UT__Read_1__1__refUT(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __location_ref_ptr);

void System_Threading_Volatile_void__Write_0__2__refbool_bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location_ref_ptr, int32_t value);

void System_Threading_Volatile_void__Write_0__2__refu8_u8(SG_HNDL_NULLABLE * _Nonnull __thrown, uint8_t* _Nonnull __location_ref_ptr, uint8_t value);

void System_Threading_Volatile_void__Write_0__2__reff64_f64(SG_HNDL_NULLABLE * _Nonnull __thrown, double* _Nonnull __location_ref_ptr, double value);

void System_Threading_Volatile_void__Write_0__2__refi16_i16(SG_HNDL_NULLABLE * _Nonnull __thrown, int16_t* _Nonnull __location_ref_ptr, int16_t value);

void System_Threading_Volatile_void__Write_0__2__refi32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t* _Nonnull __location_ref_ptr, int32_t value);

void System_Threading_Volatile_void__Write_0__2__refi64_i64(SG_HNDL_NULLABLE * _Nonnull __thrown, int64_t* _Nonnull __location_ref_ptr, int64_t value);

void System_Threading_Volatile_void__Write_0__2__refIntPtr_IntPtr(SG_HNDL_NULLABLE * _Nonnull __thrown, intptr_t* _Nonnull __location_ref_ptr, intptr_t value);

void System_Threading_Volatile_void__Write_0__2__refi8_i8(SG_HNDL_NULLABLE * _Nonnull __thrown, int8_t* _Nonnull __location_ref_ptr, int8_t value);

void System_Threading_Volatile_void__Write_0__2__reff32_f32(SG_HNDL_NULLABLE * _Nonnull __thrown, float* _Nonnull __location_ref_ptr, float value);

void System_Threading_Volatile_void__Write_0__2__refu16_u16(SG_HNDL_NULLABLE * _Nonnull __thrown, uint16_t* _Nonnull __location_ref_ptr, uint16_t value);

void System_Threading_Volatile_void__Write_0__2__refu32_u32(SG_HNDL_NULLABLE * _Nonnull __thrown, uint32_t* _Nonnull __location_ref_ptr, uint32_t value);

void System_Threading_Volatile_void__Write_0__2__refu64_u64(SG_HNDL_NULLABLE * _Nonnull __thrown, uint64_t* _Nonnull __location_ref_ptr, uint64_t value);

void System_Threading_Volatile_void__Write_0__2__refUIntPtr_UIntPtr(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL* _Nonnull __location_ref_ptr, SG_HNDL_NONNULL value);

void System_Threading_Volatile_void__Write_1__2__refUT_UT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __location_ref_ptr, GVAL value);

SG_HNDL_NONNULL specialize_System_Threading_Volatile_void__Write_1__2__refUT_UT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);

void invoke_System_Threading_Volatile_void__Write_1__2__refUT_UT(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __location_ref_ptr, GVAL value);

TYP System_Threading_WaitHandleCannotBeOpenedException_get_type_handle(void);

SG_HNDL_NONNULL System_Threading_WaitHandleCannotBeOpenedException_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown);

SG_HNDL_NONNULL System_Threading_WaitHandleCannotBeOpenedException_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message);

SG_HNDL_NONNULL System_Threading_WaitHandleCannotBeOpenedException_ctor_0__2__String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE innerException);

SG_HNDL_NONNULL System_Threading_WaitHandleCannotBeOpenedException_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);


#ifdef __cplusplus
}
#endif

#endif // INCLUDE_System_Threading

