// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "Microsoft_CSharp.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__BinaryOperation_0__4__CSharpBinderFlags_ExpressionType_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, int32_t operation, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__Convert_0__3__CSharpBinderFlags_Type_Type)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NONNULL type, SG_HNDL_NULLABLE context);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__GetIndex_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__GetMember_0__4__CSharpBinderFlags_String_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__Invoke_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__InvokeConstructor_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__InvokeMember_0__5__CSharpBinderFlags_String_System_Collections_Generic_IEnumerable_System_Type__Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE typeArguments, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__IsEvent_0__3__CSharpBinderFlags_String_Type)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE context);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__SetIndex_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__SetMember_0__4__CSharpBinderFlags_String_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__UnaryOperation_0__4__CSharpBinderFlags_ExpressionType_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, int32_t operation, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo);
    TYP (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_CSharpArgumentInfo__Create_0__2__CSharpArgumentInfoFlags_String)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NULLABLE name);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_type_handle)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_None)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_UseCompileTimeType)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_Constant)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_NamedArgument)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsRef)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsOut)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsStaticType)(void);
    TYP (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_type_handle)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_None)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_CheckedContext)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_InvokeSimpleName)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_InvokeSpecialName)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_BinaryOperationLogical)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ConvertExplicit)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ConvertArrayIndex)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ResultIndexed)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ValueFromCompoundAssignment)(void);
    int32_t (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ResultDiscarded)(void);
    TYP (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__2__String_Exception)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE innerException);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__2__String_Exception)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE innerException);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
} _g_Microsoft_CSharp;

static void my_init() {
    _sg_resolve_jumptable("Microsoft_CSharp", 16, &_g_Microsoft_CSharp);
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__BinaryOperation_0__4__CSharpBinderFlags_ExpressionType_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, int32_t operation, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__BinaryOperation_0__4__CSharpBinderFlags_ExpressionType_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__BinaryOperation_0__4__CSharpBinderFlags_ExpressionType_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(__thrown, flags, operation, context, argumentInfo);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__Convert_0__3__CSharpBinderFlags_Type_Type(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NONNULL type, SG_HNDL_NULLABLE context) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__Convert_0__3__CSharpBinderFlags_Type_Type) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__Convert_0__3__CSharpBinderFlags_Type_Type(__thrown, flags, type, context);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__GetIndex_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__GetIndex_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__GetIndex_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(__thrown, flags, context, argumentInfo);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__GetMember_0__4__CSharpBinderFlags_String_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__GetMember_0__4__CSharpBinderFlags_String_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__GetMember_0__4__CSharpBinderFlags_String_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(__thrown, flags, name, context, argumentInfo);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__Invoke_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__Invoke_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__Invoke_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(__thrown, flags, context, argumentInfo);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__InvokeConstructor_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__InvokeConstructor_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__InvokeConstructor_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(__thrown, flags, context, argumentInfo);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__InvokeMember_0__5__CSharpBinderFlags_String_System_Collections_Generic_IEnumerable_System_Type__Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE typeArguments, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__InvokeMember_0__5__CSharpBinderFlags_String_System_Collections_Generic_IEnumerable_System_Type__Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__InvokeMember_0__5__CSharpBinderFlags_String_System_Collections_Generic_IEnumerable_System_Type__Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(__thrown, flags, name, typeArguments, context, argumentInfo);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__IsEvent_0__3__CSharpBinderFlags_String_Type(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE context) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__IsEvent_0__3__CSharpBinderFlags_String_Type) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__IsEvent_0__3__CSharpBinderFlags_String_Type(__thrown, flags, name, context);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__SetIndex_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__SetIndex_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__SetIndex_0__3__CSharpBinderFlags_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(__thrown, flags, context, argumentInfo);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__SetMember_0__4__CSharpBinderFlags_String_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NONNULL name, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__SetMember_0__4__CSharpBinderFlags_String_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__SetMember_0__4__CSharpBinderFlags_String_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(__thrown, flags, name, context, argumentInfo);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__UnaryOperation_0__4__CSharpBinderFlags_ExpressionType_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, int32_t operation, SG_HNDL_NULLABLE context, SG_HNDL_NULLABLE argumentInfo) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__UnaryOperation_0__4__CSharpBinderFlags_ExpressionType_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_Binder_CallSiteBinder__UnaryOperation_0__4__CSharpBinderFlags_ExpressionType_Type_System_Collections_Generic_IEnumerable_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_(__thrown, flags, operation, context, argumentInfo);
    return ret;
}

TYP Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_get_type_handle(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_CSharpArgumentInfo__Create_0__2__CSharpArgumentInfoFlags_String(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t flags, SG_HNDL_NULLABLE name) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_CSharpArgumentInfo__Create_0__2__CSharpArgumentInfoFlags_String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_CSharpArgumentInfo__Create_0__2__CSharpArgumentInfoFlags_String(__thrown, flags, name);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfo_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_type_handle(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_type_handle();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_None(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_None) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_None();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_UseCompileTimeType(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_UseCompileTimeType) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_UseCompileTimeType();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_Constant(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_Constant) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_Constant();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_NamedArgument(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_NamedArgument) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_NamedArgument();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsRef(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsRef) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsRef();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsOut(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsOut) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsOut();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsStaticType(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsStaticType) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpArgumentInfoFlags_get_IsStaticType();
    return ret;
}

TYP Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_type_handle(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_type_handle();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_None(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_None) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_None();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_CheckedContext(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_CheckedContext) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_CheckedContext();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_InvokeSimpleName(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_InvokeSimpleName) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_InvokeSimpleName();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_InvokeSpecialName(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_InvokeSpecialName) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_InvokeSpecialName();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_BinaryOperationLogical(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_BinaryOperationLogical) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_BinaryOperationLogical();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ConvertExplicit(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ConvertExplicit) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ConvertExplicit();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ConvertArrayIndex(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ConvertArrayIndex) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ConvertArrayIndex();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ResultIndexed(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ResultIndexed) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ResultIndexed();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ValueFromCompoundAssignment(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ValueFromCompoundAssignment) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ValueFromCompoundAssignment();
    return ret;
}

int32_t Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ResultDiscarded(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ResultDiscarded) {
        my_init();
    }
    int32_t ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_CSharpBinderFlags_get_ResultDiscarded();
    return ret;
}

TYP Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_get_type_handle(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__1__String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__1__String(__thrown, message);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__2__String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE innerException) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__2__String_Exception) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_ctor_0__2__String_Exception(__thrown, message, innerException);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderException_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_get_type_handle(void) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__1__String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__1__String(__thrown, message);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__2__String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE innerException) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__2__String_Exception) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_ctor_0__2__String_Exception(__thrown, message, innerException);
    return ret;
}

SG_HNDL_NONNULL Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_CSharp._fp_Microsoft_CSharp_RuntimeBinder_RuntimeBinderInternalCompilerException_cast(__thrown, __h);
    return ret;
}

