// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "System_Threading_Overlapped.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    TYP (* _Nonnull  _fp_System_Threading_IOCompletionCallback_get_type_handle)(void);
    void (* _Nonnull  _fp_System_Threading_IOCompletionCallback_void__EndInvoke_0__1__IAsyncResult)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE result);
    TYP (* _Nonnull  _fp_System_Threading_NativeOverlapped_get_type_handle)(void);
    intptr_t (* _Nonnull  _fp_System_Threading_NativeOverlapped_get_EventHandle)(SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Threading_NativeOverlapped_set_EventHandle)(SG_HNDL_NONNULL __self_h, intptr_t __v);
    intptr_t (* _Nonnull  _fp_System_Threading_NativeOverlapped_get_InternalHigh)(SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Threading_NativeOverlapped_set_InternalHigh)(SG_HNDL_NONNULL __self_h, intptr_t __v);
    intptr_t (* _Nonnull  _fp_System_Threading_NativeOverlapped_get_InternalLow)(SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Threading_NativeOverlapped_set_InternalLow)(SG_HNDL_NONNULL __self_h, intptr_t __v);
    int32_t (* _Nonnull  _fp_System_Threading_NativeOverlapped_get_OffsetHigh)(SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Threading_NativeOverlapped_set_OffsetHigh)(SG_HNDL_NONNULL __self_h, int32_t __v);
    int32_t (* _Nonnull  _fp_System_Threading_NativeOverlapped_get_OffsetLow)(SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Threading_NativeOverlapped_set_OffsetLow)(SG_HNDL_NONNULL __self_h, int32_t __v);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_NativeOverlapped_implicit_ctor)(void);
    TYP (* _Nonnull  _fp_System_Threading_Overlapped_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_Overlapped_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_Overlapped_ctor_0__4__i32_i32_i32_IAsyncResult)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t offsetLo, int32_t offsetHi, int32_t hEvent, SG_HNDL_NULLABLE ar);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_Overlapped_ctor_0__4__i32_i32_IntPtr_IAsyncResult)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t offsetLo, int32_t offsetHi, intptr_t hEvent, SG_HNDL_NULLABLE ar);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Threading_Overlapped_IAsyncResult__get_AsyncResult_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Threading_Overlapped_void__set_AsyncResult_0__1__IAsyncResult)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value);
    int32_t (* _Nonnull  _fp_System_Threading_Overlapped_i32__get_EventHandle_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Threading_Overlapped_void__set_EventHandle_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    intptr_t (* _Nonnull  _fp_System_Threading_Overlapped_IntPtr__get_EventHandleIntPtr_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Threading_Overlapped_void__set_EventHandleIntPtr_0__1__IntPtr)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, intptr_t value);
    int32_t (* _Nonnull  _fp_System_Threading_Overlapped_i32__get_OffsetHigh_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Threading_Overlapped_void__set_OffsetHigh_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    int32_t (* _Nonnull  _fp_System_Threading_Overlapped_i32__get_OffsetLow_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Threading_Overlapped_void__set_OffsetLow_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_Overlapped_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Threading_PreAllocatedOverlapped_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_PreAllocatedOverlapped_ctor_0__3__IOCompletionCallback_Object_Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL callback, SG_HNDL_NULLABLE state, SG_HNDL_NULLABLE pinData);
    void (* _Nonnull  _fp_System_Threading_PreAllocatedOverlapped_void__Dispose_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_PreAllocatedOverlapped_PreAllocatedOverlapped__UnsafeCreate_0__3__IOCompletionCallback_Object_Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL callback, SG_HNDL_NULLABLE state, SG_HNDL_NULLABLE pinData);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_PreAllocatedOverlapped_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Threading_ThreadPoolBoundHandle_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_ThreadPoolBoundHandle_ThreadPoolBoundHandle__BindHandle_0__1__SafeHandle)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL handle);
    void (* _Nonnull  _fp_System_Threading_ThreadPoolBoundHandle_void__Dispose_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_ThreadPoolBoundHandle_SafeHandle__get_Handle_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Threading_ThreadPoolBoundHandle_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
} _g_System_Threading_Overlapped;

static void my_init() {
    _sg_resolve_jumptable("System_Threading_Overlapped", 27, &_g_System_Threading_Overlapped);
}

TYP System_Threading_IOCompletionCallback_get_type_handle(void) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_IOCompletionCallback_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Threading_Overlapped._fp_System_Threading_IOCompletionCallback_get_type_handle();
    return ret;
}

void System_Threading_IOCompletionCallback_void__EndInvoke_0__1__IAsyncResult(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE result) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_IOCompletionCallback_void__EndInvoke_0__1__IAsyncResult) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_IOCompletionCallback_void__EndInvoke_0__1__IAsyncResult(__thrown, __self_h, result);
}

TYP System_Threading_NativeOverlapped_get_type_handle(void) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_type_handle();
    return ret;
}

intptr_t System_Threading_NativeOverlapped_get_EventHandle(SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_EventHandle) {
        my_init();
    }
    intptr_t ret = _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_EventHandle(__self_h);
    return ret;
}

void System_Threading_NativeOverlapped_set_EventHandle(SG_HNDL_NONNULL __self_h, intptr_t __v) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_set_EventHandle) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_set_EventHandle(__self_h, __v);
}

intptr_t System_Threading_NativeOverlapped_get_InternalHigh(SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_InternalHigh) {
        my_init();
    }
    intptr_t ret = _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_InternalHigh(__self_h);
    return ret;
}

void System_Threading_NativeOverlapped_set_InternalHigh(SG_HNDL_NONNULL __self_h, intptr_t __v) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_set_InternalHigh) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_set_InternalHigh(__self_h, __v);
}

intptr_t System_Threading_NativeOverlapped_get_InternalLow(SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_InternalLow) {
        my_init();
    }
    intptr_t ret = _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_InternalLow(__self_h);
    return ret;
}

void System_Threading_NativeOverlapped_set_InternalLow(SG_HNDL_NONNULL __self_h, intptr_t __v) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_set_InternalLow) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_set_InternalLow(__self_h, __v);
}

int32_t System_Threading_NativeOverlapped_get_OffsetHigh(SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_OffsetHigh) {
        my_init();
    }
    int32_t ret = _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_OffsetHigh(__self_h);
    return ret;
}

void System_Threading_NativeOverlapped_set_OffsetHigh(SG_HNDL_NONNULL __self_h, int32_t __v) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_set_OffsetHigh) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_set_OffsetHigh(__self_h, __v);
}

int32_t System_Threading_NativeOverlapped_get_OffsetLow(SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_OffsetLow) {
        my_init();
    }
    int32_t ret = _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_get_OffsetLow(__self_h);
    return ret;
}

void System_Threading_NativeOverlapped_set_OffsetLow(SG_HNDL_NONNULL __self_h, int32_t __v) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_set_OffsetLow) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_set_OffsetLow(__self_h, __v);
}

SG_HNDL_NONNULL System_Threading_NativeOverlapped_implicit_ctor(void) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_implicit_ctor) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_NativeOverlapped_implicit_ctor();
    return ret;
}

TYP System_Threading_Overlapped_get_type_handle(void) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Threading_Overlapped_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Threading_Overlapped_ctor_0__4__i32_i32_i32_IAsyncResult(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t offsetLo, int32_t offsetHi, int32_t hEvent, SG_HNDL_NULLABLE ar) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_ctor_0__4__i32_i32_i32_IAsyncResult) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_ctor_0__4__i32_i32_i32_IAsyncResult(__thrown, offsetLo, offsetHi, hEvent, ar);
    return ret;
}

SG_HNDL_NONNULL System_Threading_Overlapped_ctor_0__4__i32_i32_IntPtr_IAsyncResult(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t offsetLo, int32_t offsetHi, intptr_t hEvent, SG_HNDL_NULLABLE ar) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_ctor_0__4__i32_i32_IntPtr_IAsyncResult) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_ctor_0__4__i32_i32_IntPtr_IAsyncResult(__thrown, offsetLo, offsetHi, hEvent, ar);
    return ret;
}

SG_HNDL_NULLABLE System_Threading_Overlapped_IAsyncResult__get_AsyncResult_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_IAsyncResult__get_AsyncResult_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_IAsyncResult__get_AsyncResult_0__0(__thrown, __self_h);
    return ret;
}

void System_Threading_Overlapped_void__set_AsyncResult_0__1__IAsyncResult(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_void__set_AsyncResult_0__1__IAsyncResult) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_void__set_AsyncResult_0__1__IAsyncResult(__thrown, __self_h, value);
}

int32_t System_Threading_Overlapped_i32__get_EventHandle_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_i32__get_EventHandle_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_i32__get_EventHandle_0__0(__thrown, __self_h);
    return ret;
}

void System_Threading_Overlapped_void__set_EventHandle_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_void__set_EventHandle_0__1__i32) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_void__set_EventHandle_0__1__i32(__thrown, __self_h, value);
}

intptr_t System_Threading_Overlapped_IntPtr__get_EventHandleIntPtr_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_IntPtr__get_EventHandleIntPtr_0__0) {
        my_init();
    }
    intptr_t ret = _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_IntPtr__get_EventHandleIntPtr_0__0(__thrown, __self_h);
    return ret;
}

void System_Threading_Overlapped_void__set_EventHandleIntPtr_0__1__IntPtr(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, intptr_t value) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_void__set_EventHandleIntPtr_0__1__IntPtr) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_void__set_EventHandleIntPtr_0__1__IntPtr(__thrown, __self_h, value);
}

int32_t System_Threading_Overlapped_i32__get_OffsetHigh_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_i32__get_OffsetHigh_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_i32__get_OffsetHigh_0__0(__thrown, __self_h);
    return ret;
}

void System_Threading_Overlapped_void__set_OffsetHigh_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_void__set_OffsetHigh_0__1__i32) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_void__set_OffsetHigh_0__1__i32(__thrown, __self_h, value);
}

int32_t System_Threading_Overlapped_i32__get_OffsetLow_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_i32__get_OffsetLow_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_i32__get_OffsetLow_0__0(__thrown, __self_h);
    return ret;
}

void System_Threading_Overlapped_void__set_OffsetLow_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_void__set_OffsetLow_0__1__i32) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_void__set_OffsetLow_0__1__i32(__thrown, __self_h, value);
}

SG_HNDL_NONNULL System_Threading_Overlapped_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_Overlapped_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_Overlapped_cast(__thrown, __h);
    return ret;
}

TYP System_Threading_PreAllocatedOverlapped_get_type_handle(void) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_PreAllocatedOverlapped_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Threading_Overlapped._fp_System_Threading_PreAllocatedOverlapped_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Threading_PreAllocatedOverlapped_ctor_0__3__IOCompletionCallback_Object_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL callback, SG_HNDL_NULLABLE state, SG_HNDL_NULLABLE pinData) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_PreAllocatedOverlapped_ctor_0__3__IOCompletionCallback_Object_Object) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_PreAllocatedOverlapped_ctor_0__3__IOCompletionCallback_Object_Object(__thrown, callback, state, pinData);
    return ret;
}

void System_Threading_PreAllocatedOverlapped_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_PreAllocatedOverlapped_void__Dispose_0__0) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_PreAllocatedOverlapped_void__Dispose_0__0(__thrown, __self_h);
}

SG_HNDL_NONNULL System_Threading_PreAllocatedOverlapped_PreAllocatedOverlapped__UnsafeCreate_0__3__IOCompletionCallback_Object_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL callback, SG_HNDL_NULLABLE state, SG_HNDL_NULLABLE pinData) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_PreAllocatedOverlapped_PreAllocatedOverlapped__UnsafeCreate_0__3__IOCompletionCallback_Object_Object) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_PreAllocatedOverlapped_PreAllocatedOverlapped__UnsafeCreate_0__3__IOCompletionCallback_Object_Object(__thrown, callback, state, pinData);
    return ret;
}

SG_HNDL_NONNULL System_Threading_PreAllocatedOverlapped_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_PreAllocatedOverlapped_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_PreAllocatedOverlapped_cast(__thrown, __h);
    return ret;
}

TYP System_Threading_ThreadPoolBoundHandle_get_type_handle(void) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_ThreadPoolBoundHandle_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Threading_Overlapped._fp_System_Threading_ThreadPoolBoundHandle_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Threading_ThreadPoolBoundHandle_ThreadPoolBoundHandle__BindHandle_0__1__SafeHandle(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL handle) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_ThreadPoolBoundHandle_ThreadPoolBoundHandle__BindHandle_0__1__SafeHandle) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_ThreadPoolBoundHandle_ThreadPoolBoundHandle__BindHandle_0__1__SafeHandle(__thrown, handle);
    return ret;
}

void System_Threading_ThreadPoolBoundHandle_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_ThreadPoolBoundHandle_void__Dispose_0__0) {
        my_init();
    }
    _g_System_Threading_Overlapped._fp_System_Threading_ThreadPoolBoundHandle_void__Dispose_0__0(__thrown, __self_h);
}

SG_HNDL_NONNULL System_Threading_ThreadPoolBoundHandle_SafeHandle__get_Handle_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_ThreadPoolBoundHandle_SafeHandle__get_Handle_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_ThreadPoolBoundHandle_SafeHandle__get_Handle_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Threading_ThreadPoolBoundHandle_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Threading_Overlapped._fp_System_Threading_ThreadPoolBoundHandle_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Threading_Overlapped._fp_System_Threading_ThreadPoolBoundHandle_cast(__thrown, __h);
    return ret;
}

