// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "System_Web_HttpUtility.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    TYP (* _Nonnull  _fp_System_Web_HttpUtility_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Web_HttpUtility_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__HtmlAttributeEncode_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s);
    void (* _Nonnull  _fp_System_Web_HttpUtility_void__HtmlAttributeEncode_0__2__String_TextWriter)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s, SG_HNDL_NONNULL output);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__HtmlDecode_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s);
    void (* _Nonnull  _fp_System_Web_HttpUtility_void__HtmlDecode_0__2__String_TextWriter)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s, SG_HNDL_NONNULL output);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__HtmlEncode_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE value);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__HtmlEncode_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s);
    void (* _Nonnull  _fp_System_Web_HttpUtility_void__HtmlEncode_0__2__String_TextWriter)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s, SG_HNDL_NONNULL output);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Web_HttpUtility_String__JavaScriptStringEncode_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Web_HttpUtility_String__JavaScriptStringEncode_0__2__String_bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE value, int32_t addDoubleQuotes);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Web_HttpUtility_NameValueCollection__ParseQueryString_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL query);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Web_HttpUtility_NameValueCollection__ParseQueryString_0__2__String_Encoding)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL query, SG_HNDL_NONNULL encoding);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__UrlDecode_0__4__u8Array_i32_i32_Encoding)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes, int32_t offset, int32_t count, SG_HNDL_NONNULL e);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__UrlDecode_0__2__u8Array_Encoding)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes, SG_HNDL_NONNULL e);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__UrlDecode_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__UrlDecode_0__2__String_Encoding)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str, SG_HNDL_NONNULL e);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__1__u8Array)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__3__u8Array_i32_i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes, int32_t offset, int32_t count);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__2__String_Encoding)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str, SG_HNDL_NONNULL e);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__UrlEncode_0__1__u8Array)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__UrlEncode_0__3__u8Array_i32_i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes, int32_t offset, int32_t count);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__UrlEncode_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__UrlEncode_0__2__String_Encoding)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str, SG_HNDL_NONNULL e);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__1__u8Array)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__3__u8Array_i32_i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes, int32_t offset, int32_t count);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__2__String_Encoding)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str, SG_HNDL_NONNULL e);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__UrlEncodeUnicode_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_u8Array__UrlEncodeUnicodeToBytes_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Web_HttpUtility_String__UrlPathEncode_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Web_HttpUtility_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
} _g_System_Web_HttpUtility;

static void my_init() {
    _sg_resolve_jumptable("System_Web_HttpUtility", 22, &_g_System_Web_HttpUtility);
}

TYP System_Web_HttpUtility_get_type_handle(void) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Web_HttpUtility_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__HtmlAttributeEncode_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__HtmlAttributeEncode_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__HtmlAttributeEncode_0__1__String(__thrown, s);
    return ret;
}

void System_Web_HttpUtility_void__HtmlAttributeEncode_0__2__String_TextWriter(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s, SG_HNDL_NONNULL output) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_void__HtmlAttributeEncode_0__2__String_TextWriter) {
        my_init();
    }
    _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_void__HtmlAttributeEncode_0__2__String_TextWriter(__thrown, s, output);
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__HtmlDecode_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__HtmlDecode_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__HtmlDecode_0__1__String(__thrown, s);
    return ret;
}

void System_Web_HttpUtility_void__HtmlDecode_0__2__String_TextWriter(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s, SG_HNDL_NONNULL output) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_void__HtmlDecode_0__2__String_TextWriter) {
        my_init();
    }
    _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_void__HtmlDecode_0__2__String_TextWriter(__thrown, s, output);
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__HtmlEncode_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE value) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__HtmlEncode_0__1__Object) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__HtmlEncode_0__1__Object(__thrown, value);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__HtmlEncode_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__HtmlEncode_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__HtmlEncode_0__1__String(__thrown, s);
    return ret;
}

void System_Web_HttpUtility_void__HtmlEncode_0__2__String_TextWriter(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE s, SG_HNDL_NONNULL output) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_void__HtmlEncode_0__2__String_TextWriter) {
        my_init();
    }
    _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_void__HtmlEncode_0__2__String_TextWriter(__thrown, s, output);
}

SG_HNDL_NONNULL System_Web_HttpUtility_String__JavaScriptStringEncode_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE value) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__JavaScriptStringEncode_0__1__String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__JavaScriptStringEncode_0__1__String(__thrown, value);
    return ret;
}

SG_HNDL_NONNULL System_Web_HttpUtility_String__JavaScriptStringEncode_0__2__String_bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE value, int32_t addDoubleQuotes) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__JavaScriptStringEncode_0__2__String_bool) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__JavaScriptStringEncode_0__2__String_bool(__thrown, value, addDoubleQuotes);
    return ret;
}

SG_HNDL_NONNULL System_Web_HttpUtility_NameValueCollection__ParseQueryString_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL query) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_NameValueCollection__ParseQueryString_0__1__String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_NameValueCollection__ParseQueryString_0__1__String(__thrown, query);
    return ret;
}

SG_HNDL_NONNULL System_Web_HttpUtility_NameValueCollection__ParseQueryString_0__2__String_Encoding(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL query, SG_HNDL_NONNULL encoding) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_NameValueCollection__ParseQueryString_0__2__String_Encoding) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_NameValueCollection__ParseQueryString_0__2__String_Encoding(__thrown, query, encoding);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__UrlDecode_0__4__u8Array_i32_i32_Encoding(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes, int32_t offset, int32_t count, SG_HNDL_NONNULL e) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlDecode_0__4__u8Array_i32_i32_Encoding) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlDecode_0__4__u8Array_i32_i32_Encoding(__thrown, bytes, offset, count, e);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__UrlDecode_0__2__u8Array_Encoding(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes, SG_HNDL_NONNULL e) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlDecode_0__2__u8Array_Encoding) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlDecode_0__2__u8Array_Encoding(__thrown, bytes, e);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__UrlDecode_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlDecode_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlDecode_0__1__String(__thrown, str);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__UrlDecode_0__2__String_Encoding(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str, SG_HNDL_NONNULL e) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlDecode_0__2__String_Encoding) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlDecode_0__2__String_Encoding(__thrown, str, e);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__1__u8Array(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__1__u8Array) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__1__u8Array(__thrown, bytes);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__3__u8Array_i32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes, int32_t offset, int32_t count) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__3__u8Array_i32_i32) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__3__u8Array_i32_i32(__thrown, bytes, offset, count);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__1__String(__thrown, str);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__2__String_Encoding(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str, SG_HNDL_NONNULL e) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__2__String_Encoding) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlDecodeToBytes_0__2__String_Encoding(__thrown, str, e);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__UrlEncode_0__1__u8Array(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlEncode_0__1__u8Array) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlEncode_0__1__u8Array(__thrown, bytes);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__UrlEncode_0__3__u8Array_i32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes, int32_t offset, int32_t count) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlEncode_0__3__u8Array_i32_i32) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlEncode_0__3__u8Array_i32_i32(__thrown, bytes, offset, count);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__UrlEncode_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlEncode_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlEncode_0__1__String(__thrown, str);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__UrlEncode_0__2__String_Encoding(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str, SG_HNDL_NONNULL e) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlEncode_0__2__String_Encoding) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlEncode_0__2__String_Encoding(__thrown, str, e);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__1__u8Array(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__1__u8Array) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__1__u8Array(__thrown, bytes);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__3__u8Array_i32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE bytes, int32_t offset, int32_t count) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__3__u8Array_i32_i32) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__3__u8Array_i32_i32(__thrown, bytes, offset, count);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__1__String(__thrown, str);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__2__String_Encoding(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str, SG_HNDL_NONNULL e) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__2__String_Encoding) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlEncodeToBytes_0__2__String_Encoding(__thrown, str, e);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__UrlEncodeUnicode_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlEncodeUnicode_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlEncodeUnicode_0__1__String(__thrown, str);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_u8Array__UrlEncodeUnicodeToBytes_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlEncodeUnicodeToBytes_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_u8Array__UrlEncodeUnicodeToBytes_0__1__String(__thrown, str);
    return ret;
}

SG_HNDL_NULLABLE System_Web_HttpUtility_String__UrlPathEncode_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE str) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlPathEncode_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_String__UrlPathEncode_0__1__String(__thrown, str);
    return ret;
}

SG_HNDL_NONNULL System_Web_HttpUtility_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Web_HttpUtility._fp_System_Web_HttpUtility_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Web_HttpUtility._fp_System_Web_HttpUtility_cast(__thrown, __h);
    return ret;
}

