// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "System_Diagnostics_Tools.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
} _g_System_Diagnostics_Tools;

static void my_init() {
    _sg_resolve_jumptable("System_Diagnostics_Tools", 24, &_g_System_Diagnostics_Tools);
}

