// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "System_Runtime_CompilerServices_VisualC.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    TYP (* _Nonnull  _fp_System_Runtime_CompilerServices_CppInlineNamespaceAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_CppInlineNamespaceAttribute_ctor_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL dottedName);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_CppInlineNamespaceAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Runtime_CompilerServices_HasCopySemanticsAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_HasCopySemanticsAttribute_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_HasCopySemanticsAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Runtime_CompilerServices_NativeCppClassAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_NativeCppClassAttribute_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_NativeCppClassAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_ctor_0__1__Type)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL requiredContract);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_Type__get_RequiredContract_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Runtime_CompilerServices_ScopelessEnumAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_ScopelessEnumAttribute_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Runtime_CompilerServices_ScopelessEnumAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
} _g_System_Runtime_CompilerServices_VisualC;

static void my_init() {
    _sg_resolve_jumptable("System_Runtime_CompilerServices_VisualC", 39, &_g_System_Runtime_CompilerServices_VisualC);
}

TYP System_Runtime_CompilerServices_CppInlineNamespaceAttribute_get_type_handle(void) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_CppInlineNamespaceAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_CppInlineNamespaceAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_CppInlineNamespaceAttribute_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL dottedName) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_CppInlineNamespaceAttribute_ctor_0__1__String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_CppInlineNamespaceAttribute_ctor_0__1__String(__thrown, dottedName);
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_CppInlineNamespaceAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_CppInlineNamespaceAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_CppInlineNamespaceAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Runtime_CompilerServices_HasCopySemanticsAttribute_get_type_handle(void) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_HasCopySemanticsAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_HasCopySemanticsAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_HasCopySemanticsAttribute_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_HasCopySemanticsAttribute_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_HasCopySemanticsAttribute_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_HasCopySemanticsAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_HasCopySemanticsAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_HasCopySemanticsAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Runtime_CompilerServices_NativeCppClassAttribute_get_type_handle(void) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_NativeCppClassAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_NativeCppClassAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_NativeCppClassAttribute_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_NativeCppClassAttribute_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_NativeCppClassAttribute_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_NativeCppClassAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_NativeCppClassAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_NativeCppClassAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Runtime_CompilerServices_RequiredAttributeAttribute_get_type_handle(void) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_RequiredAttributeAttribute_ctor_0__1__Type(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL requiredContract) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_ctor_0__1__Type) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_ctor_0__1__Type(__thrown, requiredContract);
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_RequiredAttributeAttribute_Type__get_RequiredContract_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_Type__get_RequiredContract_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_Type__get_RequiredContract_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_RequiredAttributeAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_RequiredAttributeAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Runtime_CompilerServices_ScopelessEnumAttribute_get_type_handle(void) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_ScopelessEnumAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_ScopelessEnumAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_ScopelessEnumAttribute_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_ScopelessEnumAttribute_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_ScopelessEnumAttribute_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Runtime_CompilerServices_ScopelessEnumAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_ScopelessEnumAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Runtime_CompilerServices_VisualC._fp_System_Runtime_CompilerServices_ScopelessEnumAttribute_cast(__thrown, __h);
    return ret;
}

