// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "System_Diagnostics_FileVersionInfo.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    TYP (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_FileVersionInfo__GetVersionInfo_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL fileName);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__ToString_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_Comments_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_CompanyName_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_i32__get_FileBuildPart_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_FileDescription_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_i32__get_FileMajorPart_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_i32__get_FileMinorPart_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_FileName_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_i32__get_FilePrivatePart_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_FileVersion_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_InternalName_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_bool__get_IsDebug_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_bool__get_IsPatched_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_bool__get_IsPreRelease_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_bool__get_IsPrivateBuild_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_bool__get_IsSpecialBuild_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_Language_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_LegalCopyright_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_LegalTrademarks_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_OriginalFilename_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_PrivateBuild_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_i32__get_ProductBuildPart_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_i32__get_ProductMajorPart_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_i32__get_ProductMinorPart_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_ProductName_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_i32__get_ProductPrivatePart_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_ProductVersion_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_String__get_SpecialBuild_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_FileVersionInfo_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
} _g_System_Diagnostics_FileVersionInfo;

static void my_init() {
    _sg_resolve_jumptable("System_Diagnostics_FileVersionInfo", 34, &_g_System_Diagnostics_FileVersionInfo);
}

TYP System_Diagnostics_FileVersionInfo_get_type_handle(void) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_FileVersionInfo_FileVersionInfo__GetVersionInfo_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL fileName) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_FileVersionInfo__GetVersionInfo_0__1__String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_FileVersionInfo__GetVersionInfo_0__1__String(__thrown, fileName);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_FileVersionInfo_String__ToString_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__ToString_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__ToString_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_Comments_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_Comments_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_Comments_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_CompanyName_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_CompanyName_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_CompanyName_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_i32__get_FileBuildPart_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_FileBuildPart_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_FileBuildPart_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_FileDescription_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_FileDescription_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_FileDescription_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_i32__get_FileMajorPart_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_FileMajorPart_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_FileMajorPart_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_i32__get_FileMinorPart_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_FileMinorPart_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_FileMinorPart_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_FileVersionInfo_String__get_FileName_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_FileName_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_FileName_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_i32__get_FilePrivatePart_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_FilePrivatePart_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_FilePrivatePart_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_FileVersion_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_FileVersion_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_FileVersion_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_InternalName_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_InternalName_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_InternalName_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_bool__get_IsDebug_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_bool__get_IsDebug_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_bool__get_IsDebug_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_bool__get_IsPatched_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_bool__get_IsPatched_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_bool__get_IsPatched_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_bool__get_IsPreRelease_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_bool__get_IsPreRelease_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_bool__get_IsPreRelease_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_bool__get_IsPrivateBuild_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_bool__get_IsPrivateBuild_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_bool__get_IsPrivateBuild_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_bool__get_IsSpecialBuild_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_bool__get_IsSpecialBuild_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_bool__get_IsSpecialBuild_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_Language_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_Language_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_Language_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_LegalCopyright_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_LegalCopyright_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_LegalCopyright_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_LegalTrademarks_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_LegalTrademarks_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_LegalTrademarks_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_OriginalFilename_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_OriginalFilename_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_OriginalFilename_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_PrivateBuild_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_PrivateBuild_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_PrivateBuild_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_i32__get_ProductBuildPart_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_ProductBuildPart_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_ProductBuildPart_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_i32__get_ProductMajorPart_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_ProductMajorPart_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_ProductMajorPart_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_i32__get_ProductMinorPart_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_ProductMinorPart_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_ProductMinorPart_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_ProductName_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_ProductName_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_ProductName_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_FileVersionInfo_i32__get_ProductPrivatePart_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_ProductPrivatePart_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_i32__get_ProductPrivatePart_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_ProductVersion_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_ProductVersion_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_ProductVersion_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_FileVersionInfo_String__get_SpecialBuild_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_SpecialBuild_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_String__get_SpecialBuild_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_FileVersionInfo_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_FileVersionInfo._fp_System_Diagnostics_FileVersionInfo_cast(__thrown, __h);
    return ret;
}

