// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "System_Diagnostics_Contracts.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Assert_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Assert_0__2__bool_String)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Assume_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Assume_0__2__bool_String)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__EndContractBlock_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Ensures_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Ensures_0__2__bool_String)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool)(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool)(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown);
    void (* _Nonnull  _fp_invoke_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String)(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String)(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown);
    void (* _Nonnull  _fp_invoke_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_bool__Exists_0__3__i32_i32_System_Predicate_i32_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t fromInclusive, int32_t toExclusive, SG_HNDL_NONNULL predicate);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL collection, SG_HNDL_NONNULL predicate);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);
    int32_t (* _Nonnull  _fp_invoke_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL collection, SG_HNDL_NONNULL predicate);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_bool__ForAll_0__3__i32_i32_System_Predicate_i32_)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t fromInclusive, int32_t toExclusive, SG_HNDL_NONNULL predicate);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL collection, SG_HNDL_NONNULL predicate);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);
    int32_t (* _Nonnull  _fp_invoke_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL collection, SG_HNDL_NONNULL predicate);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Invariant_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Invariant_0__2__bool_String)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage);
    GVAL (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);
    GVAL (* _Nonnull  _fp_invoke_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL value);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Requires_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Requires_0__2__bool_String)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool)(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool)(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown);
    void (* _Nonnull  _fp_invoke_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String)(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String)(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown);
    void (* _Nonnull  _fp_invoke_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage);
    GVAL (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_UT__Result_1__0)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_System_Diagnostics_Contracts_Contract_UT__Result_1__0)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);
    GVAL (* _Nonnull  _fp_invoke_System_Diagnostics_Contracts_Contract_UT__Result_1__0)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown);
    GVAL (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __value_out_ptr);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);
    GVAL (* _Nonnull  _fp_invoke_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __value_out_ptr);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__add_ContractFailed_0__1__System_EventHandler_System_Diagnostics_Contracts_ContractFailedEventArgs_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE value);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_Contract_void__remove_ContractFailed_0__1__System_EventHandler_System_Diagnostics_Contracts_ContractFailedEventArgs_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE value);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractAbbreviatorAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractAbbreviatorAttribute_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractAbbreviatorAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractClassAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractClassAttribute_ctor_0__1__Type)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL typeContainingContracts);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractClassAttribute_Type__get_TypeContainingContracts_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractClassAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractClassForAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractClassForAttribute_ctor_0__1__Type)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL typeContractsAreFor);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractClassForAttribute_Type__get_TypeContractsAreFor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractClassForAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_ctor_0__4__ContractFailureKind_String_String_Exception)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t failureKind, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE condition, SG_HNDL_NULLABLE originalException);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_void__SetHandled_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_void__SetUnwind_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_String__get_Condition_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_ContractFailureKind__get_FailureKind_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_bool__get_Handled_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_String__get_Message_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_Exception__get_OriginalException_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_bool__get_Unwind_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailedEventArgs_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailureKind_get_type_handle)(void);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailureKind_get_Precondition)(void);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailureKind_get_Postcondition)(void);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailureKind_get_PostconditionOnException)(void);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailureKind_get_Invariant)(void);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailureKind_get_Assert)(void);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractFailureKind_get_Assume)(void);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractInvariantMethodAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractInvariantMethodAttribute_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractInvariantMethodAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractOptionAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractOptionAttribute_ctor_0__3__String_String_bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL category, SG_HNDL_NONNULL setting, int32_t enabled);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractOptionAttribute_ctor_0__3__String_String_String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL category, SG_HNDL_NONNULL setting, SG_HNDL_NONNULL value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Category_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractOptionAttribute_bool__get_Enabled_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Setting_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Value_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractOptionAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_ctor_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL name);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_String__get_Name_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractVerificationAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractVerificationAttribute_ctor_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t value);
    int32_t (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractVerificationAttribute_bool__get_Value_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_ContractVerificationAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Diagnostics_Contracts_PureAttribute_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_PureAttribute_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Diagnostics_Contracts_PureAttribute_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Runtime_CompilerServices_ContractHelper_String__RaiseContractFailedEvent_0__4__ContractFailureKind_String_String_Exception)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t failureKind, SG_HNDL_NULLABLE userMessage, SG_HNDL_NULLABLE conditionText, SG_HNDL_NULLABLE innerException);
    void (* _Nonnull  _fp_System_Runtime_CompilerServices_ContractHelper_void__TriggerFailure_0__5__ContractFailureKind_String_String_String_Exception)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t kind, SG_HNDL_NULLABLE displayMessage, SG_HNDL_NULLABLE userMessage, SG_HNDL_NULLABLE conditionText, SG_HNDL_NULLABLE innerException);
} _g_System_Diagnostics_Contracts;

static void my_init() {
    _sg_resolve_jumptable("System_Diagnostics_Contracts", 28, &_g_System_Diagnostics_Contracts);
}

void System_Diagnostics_Contracts_Contract_void__Assert_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Assert_0__1__bool) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Assert_0__1__bool(__thrown, condition);
}

void System_Diagnostics_Contracts_Contract_void__Assert_0__2__bool_String(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Assert_0__2__bool_String) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Assert_0__2__bool_String(__thrown, condition, userMessage);
}

void System_Diagnostics_Contracts_Contract_void__Assume_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Assume_0__1__bool) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Assume_0__1__bool(__thrown, condition);
}

void System_Diagnostics_Contracts_Contract_void__Assume_0__2__bool_String(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Assume_0__2__bool_String) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Assume_0__2__bool_String(__thrown, condition, userMessage);
}

void System_Diagnostics_Contracts_Contract_void__EndContractBlock_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__EndContractBlock_0__0) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__EndContractBlock_0__0(__thrown);
}

void System_Diagnostics_Contracts_Contract_void__Ensures_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Ensures_0__1__bool) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Ensures_0__1__bool(__thrown, condition);
}

void System_Diagnostics_Contracts_Contract_void__Ensures_0__2__bool_String(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Ensures_0__2__bool_String) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Ensures_0__2__bool_String(__thrown, condition, userMessage);
}

void System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool(TException, __thrown, condition);
}

SG_HNDL_NONNULL specialize_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool(TException, __thrown);
    return ret;
}

void invoke_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition) {
    if (!_g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__1__bool(____hdel, __thrown, condition);
}

void System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String(TException, __thrown, condition, userMessage);
}

SG_HNDL_NONNULL specialize_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String(TException, __thrown);
    return ret;
}

void invoke_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage) {
    if (!_g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_void__EnsuresOnThrow_1__2__bool_String(____hdel, __thrown, condition, userMessage);
}

int32_t System_Diagnostics_Contracts_Contract_bool__Exists_0__3__i32_i32_System_Predicate_i32_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t fromInclusive, int32_t toExclusive, SG_HNDL_NONNULL predicate) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_bool__Exists_0__3__i32_i32_System_Predicate_i32_) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_bool__Exists_0__3__i32_i32_System_Predicate_i32_(__thrown, fromInclusive, toExclusive, predicate);
    return ret;
}

int32_t System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL collection, SG_HNDL_NONNULL predicate) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(T, __thrown, collection, predicate);
    return ret;
}

SG_HNDL_NONNULL specialize_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(T, __thrown);
    return ret;
}

int32_t invoke_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL collection, SG_HNDL_NONNULL predicate) {
    if (!_g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_bool__Exists_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(____hdel, __thrown, collection, predicate);
    return ret;
}

int32_t System_Diagnostics_Contracts_Contract_bool__ForAll_0__3__i32_i32_System_Predicate_i32_(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t fromInclusive, int32_t toExclusive, SG_HNDL_NONNULL predicate) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_bool__ForAll_0__3__i32_i32_System_Predicate_i32_) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_bool__ForAll_0__3__i32_i32_System_Predicate_i32_(__thrown, fromInclusive, toExclusive, predicate);
    return ret;
}

int32_t System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL collection, SG_HNDL_NONNULL predicate) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(T, __thrown, collection, predicate);
    return ret;
}

SG_HNDL_NONNULL specialize_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(T, __thrown);
    return ret;
}

int32_t invoke_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL collection, SG_HNDL_NONNULL predicate) {
    if (!_g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_bool__ForAll_1__2__System_Collections_Generic_IEnumerable_UT__System_Predicate_UT_(____hdel, __thrown, collection, predicate);
    return ret;
}

void System_Diagnostics_Contracts_Contract_void__Invariant_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Invariant_0__1__bool) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Invariant_0__1__bool(__thrown, condition);
}

void System_Diagnostics_Contracts_Contract_void__Invariant_0__2__bool_String(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Invariant_0__2__bool_String) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Invariant_0__2__bool_String(__thrown, condition, userMessage);
}

GVAL System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL value) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT) {
        my_init();
    }
    GVAL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT(T, __thrown, value);
    return ret;
}

SG_HNDL_NONNULL specialize_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT(T, __thrown);
    return ret;
}

GVAL invoke_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL value) {
    if (!_g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT) {
        my_init();
    }
    GVAL ret = _g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_UT__OldValue_1__1__UT(____hdel, __thrown, value);
    return ret;
}

void System_Diagnostics_Contracts_Contract_void__Requires_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Requires_0__1__bool) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Requires_0__1__bool(__thrown, condition);
}

void System_Diagnostics_Contracts_Contract_void__Requires_0__2__bool_String(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Requires_0__2__bool_String) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Requires_0__2__bool_String(__thrown, condition, userMessage);
}

void System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool(TException, __thrown, condition);
}

SG_HNDL_NONNULL specialize_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool(TException, __thrown);
    return ret;
}

void invoke_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition) {
    if (!_g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_void__Requires_1__1__bool(____hdel, __thrown, condition);
}

void System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String(TException, __thrown, condition, userMessage);
}

SG_HNDL_NONNULL specialize_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String(TYP TException, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String(TException, __thrown);
    return ret;
}

void invoke_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t condition, SG_HNDL_NULLABLE userMessage) {
    if (!_g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_void__Requires_1__2__bool_String(____hdel, __thrown, condition, userMessage);
}

GVAL System_Diagnostics_Contracts_Contract_UT__Result_1__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_UT__Result_1__0) {
        my_init();
    }
    GVAL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_UT__Result_1__0(T, __thrown);
    return ret;
}

SG_HNDL_NONNULL specialize_System_Diagnostics_Contracts_Contract_UT__Result_1__0(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_UT__Result_1__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_UT__Result_1__0(T, __thrown);
    return ret;
}

GVAL invoke_System_Diagnostics_Contracts_Contract_UT__Result_1__0(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_UT__Result_1__0) {
        my_init();
    }
    GVAL ret = _g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_UT__Result_1__0(____hdel, __thrown);
    return ret;
}

GVAL System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __value_out_ptr) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT) {
        my_init();
    }
    GVAL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT(T, __thrown, __value_out_ptr);
    return ret;
}

SG_HNDL_NONNULL specialize_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_specialize_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT(T, __thrown);
    return ret;
}

GVAL invoke_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, GVAL* _Nonnull __value_out_ptr) {
    if (!_g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT) {
        my_init();
    }
    GVAL ret = _g_System_Diagnostics_Contracts._fp_invoke_System_Diagnostics_Contracts_Contract_UT__ValueAtReturn_1__1__outUT(____hdel, __thrown, __value_out_ptr);
    return ret;
}

void System_Diagnostics_Contracts_Contract_void__add_ContractFailed_0__1__System_EventHandler_System_Diagnostics_Contracts_ContractFailedEventArgs_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE value) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__add_ContractFailed_0__1__System_EventHandler_System_Diagnostics_Contracts_ContractFailedEventArgs_) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__add_ContractFailed_0__1__System_EventHandler_System_Diagnostics_Contracts_ContractFailedEventArgs_(__thrown, value);
}

void System_Diagnostics_Contracts_Contract_void__remove_ContractFailed_0__1__System_EventHandler_System_Diagnostics_Contracts_ContractFailedEventArgs_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE value) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__remove_ContractFailed_0__1__System_EventHandler_System_Diagnostics_Contracts_ContractFailedEventArgs_) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_Contract_void__remove_ContractFailed_0__1__System_EventHandler_System_Diagnostics_Contracts_ContractFailedEventArgs_(__thrown, value);
}

TYP System_Diagnostics_Contracts_ContractAbbreviatorAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractAbbreviatorAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractAbbreviatorAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractAbbreviatorAttribute_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractAbbreviatorAttribute_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractAbbreviatorAttribute_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractAbbreviatorAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractAbbreviatorAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractAbbreviatorAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractArgumentValidatorAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_ContractClassAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractClassAttribute_ctor_0__1__Type(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL typeContainingContracts) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassAttribute_ctor_0__1__Type) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassAttribute_ctor_0__1__Type(__thrown, typeContainingContracts);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractClassAttribute_Type__get_TypeContainingContracts_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassAttribute_Type__get_TypeContainingContracts_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassAttribute_Type__get_TypeContainingContracts_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractClassAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_ContractClassForAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassForAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassForAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractClassForAttribute_ctor_0__1__Type(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL typeContractsAreFor) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassForAttribute_ctor_0__1__Type) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassForAttribute_ctor_0__1__Type(__thrown, typeContractsAreFor);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractClassForAttribute_Type__get_TypeContractsAreFor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassForAttribute_Type__get_TypeContractsAreFor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassForAttribute_Type__get_TypeContractsAreFor_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractClassForAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassForAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractClassForAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_ContractFailedEventArgs_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractFailedEventArgs_ctor_0__4__ContractFailureKind_String_String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t failureKind, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE condition, SG_HNDL_NULLABLE originalException) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_ctor_0__4__ContractFailureKind_String_String_Exception) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_ctor_0__4__ContractFailureKind_String_String_Exception(__thrown, failureKind, message, condition, originalException);
    return ret;
}

void System_Diagnostics_Contracts_ContractFailedEventArgs_void__SetHandled_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_void__SetHandled_0__0) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_void__SetHandled_0__0(__thrown, __self_h);
}

void System_Diagnostics_Contracts_ContractFailedEventArgs_void__SetUnwind_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_void__SetUnwind_0__0) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_void__SetUnwind_0__0(__thrown, __self_h);
}

SG_HNDL_NULLABLE System_Diagnostics_Contracts_ContractFailedEventArgs_String__get_Condition_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_String__get_Condition_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_String__get_Condition_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractFailedEventArgs_ContractFailureKind__get_FailureKind_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_ContractFailureKind__get_FailureKind_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_ContractFailureKind__get_FailureKind_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractFailedEventArgs_bool__get_Handled_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_bool__get_Handled_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_bool__get_Handled_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_Contracts_ContractFailedEventArgs_String__get_Message_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_String__get_Message_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_String__get_Message_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_Contracts_ContractFailedEventArgs_Exception__get_OriginalException_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_Exception__get_OriginalException_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_Exception__get_OriginalException_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractFailedEventArgs_bool__get_Unwind_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_bool__get_Unwind_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_bool__get_Unwind_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractFailedEventArgs_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailedEventArgs_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_ContractFailureKind_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_type_handle();
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractFailureKind_get_Precondition(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_Precondition) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_Precondition();
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractFailureKind_get_Postcondition(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_Postcondition) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_Postcondition();
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractFailureKind_get_PostconditionOnException(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_PostconditionOnException) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_PostconditionOnException();
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractFailureKind_get_Invariant(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_Invariant) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_Invariant();
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractFailureKind_get_Assert(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_Assert) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_Assert();
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractFailureKind_get_Assume(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_Assume) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractFailureKind_get_Assume();
    return ret;
}

TYP System_Diagnostics_Contracts_ContractInvariantMethodAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractInvariantMethodAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractInvariantMethodAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractInvariantMethodAttribute_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractInvariantMethodAttribute_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractInvariantMethodAttribute_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractInvariantMethodAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractInvariantMethodAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractInvariantMethodAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_ContractOptionAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractOptionAttribute_ctor_0__3__String_String_bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL category, SG_HNDL_NONNULL setting, int32_t enabled) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_ctor_0__3__String_String_bool) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_ctor_0__3__String_String_bool(__thrown, category, setting, enabled);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractOptionAttribute_ctor_0__3__String_String_String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL category, SG_HNDL_NONNULL setting, SG_HNDL_NONNULL value) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_ctor_0__3__String_String_String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_ctor_0__3__String_String_String(__thrown, category, setting, value);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Category_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Category_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Category_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractOptionAttribute_bool__get_Enabled_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_bool__get_Enabled_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_bool__get_Enabled_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Setting_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Setting_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Setting_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Value_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Value_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_String__get_Value_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractOptionAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractOptionAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL name) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_ctor_0__1__String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_ctor_0__1__String(__thrown, name);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_String__get_Name_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_String__get_Name_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_String__get_Name_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractPublicPropertyNameAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractReferenceAssemblyAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractRuntimeIgnoredAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_ContractVerificationAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractVerificationAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractVerificationAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractVerificationAttribute_ctor_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t value) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractVerificationAttribute_ctor_0__1__bool) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractVerificationAttribute_ctor_0__1__bool(__thrown, value);
    return ret;
}

int32_t System_Diagnostics_Contracts_ContractVerificationAttribute_bool__get_Value_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractVerificationAttribute_bool__get_Value_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractVerificationAttribute_bool__get_Value_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_ContractVerificationAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractVerificationAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_ContractVerificationAttribute_cast(__thrown, __h);
    return ret;
}

TYP System_Diagnostics_Contracts_PureAttribute_get_type_handle(void) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_PureAttribute_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_PureAttribute_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_PureAttribute_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_PureAttribute_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_PureAttribute_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Diagnostics_Contracts_PureAttribute_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_PureAttribute_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Diagnostics_Contracts._fp_System_Diagnostics_Contracts_PureAttribute_cast(__thrown, __h);
    return ret;
}

SG_HNDL_NULLABLE System_Runtime_CompilerServices_ContractHelper_String__RaiseContractFailedEvent_0__4__ContractFailureKind_String_String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t failureKind, SG_HNDL_NULLABLE userMessage, SG_HNDL_NULLABLE conditionText, SG_HNDL_NULLABLE innerException) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Runtime_CompilerServices_ContractHelper_String__RaiseContractFailedEvent_0__4__ContractFailureKind_String_String_Exception) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Diagnostics_Contracts._fp_System_Runtime_CompilerServices_ContractHelper_String__RaiseContractFailedEvent_0__4__ContractFailureKind_String_String_Exception(__thrown, failureKind, userMessage, conditionText, innerException);
    return ret;
}

void System_Runtime_CompilerServices_ContractHelper_void__TriggerFailure_0__5__ContractFailureKind_String_String_String_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t kind, SG_HNDL_NULLABLE displayMessage, SG_HNDL_NULLABLE userMessage, SG_HNDL_NULLABLE conditionText, SG_HNDL_NULLABLE innerException) {
    if (!_g_System_Diagnostics_Contracts._fp_System_Runtime_CompilerServices_ContractHelper_void__TriggerFailure_0__5__ContractFailureKind_String_String_String_Exception) {
        my_init();
    }
    _g_System_Diagnostics_Contracts._fp_System_Runtime_CompilerServices_ContractHelper_void__TriggerFailure_0__5__ContractFailureKind_String_String_String_Exception(__thrown, kind, displayMessage, userMessage, conditionText, innerException);
}

