// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "System_Collections_NonGeneric.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    TYP (* _Nonnull  _fp_System_Collections_CaseInsensitiveComparer_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CaseInsensitiveComparer_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CaseInsensitiveComparer_ctor_0__1__CultureInfo)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL culture);
    int32_t (* _Nonnull  _fp_System_Collections_CaseInsensitiveComparer_i32__Compare_0__2__Object_Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE a, SG_HNDL_NULLABLE b);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CaseInsensitiveComparer_CaseInsensitiveComparer__get_Default_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CaseInsensitiveComparer_CaseInsensitiveComparer__get_DefaultInvariant_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CaseInsensitiveComparer_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Collections_CaseInsensitiveHashCodeProvider_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CaseInsensitiveHashCodeProvider_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CaseInsensitiveHashCodeProvider_ctor_0__1__CultureInfo)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL culture);
    int32_t (* _Nonnull  _fp_System_Collections_CaseInsensitiveHashCodeProvider_i32__GetHashCode_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL obj);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CaseInsensitiveHashCodeProvider_CaseInsensitiveHashCodeProvider__get_Default_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CaseInsensitiveHashCodeProvider_CaseInsensitiveHashCodeProvider__get_DefaultInvariant_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CaseInsensitiveHashCodeProvider_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Collections_CollectionBase_get_type_handle)(void);
    void (* _Nonnull  _fp_System_Collections_CollectionBase_void__Clear_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CollectionBase_IEnumerator__GetEnumerator_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Collections_CollectionBase_void__RemoveAt_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t index);
    int32_t (* _Nonnull  _fp_System_Collections_CollectionBase_i32__get_Capacity_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Collections_CollectionBase_void__set_Capacity_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    int32_t (* _Nonnull  _fp_System_Collections_CollectionBase_i32__get_Count_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_CollectionBase_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Collections_DictionaryBase_get_type_handle)(void);
    void (* _Nonnull  _fp_System_Collections_DictionaryBase_void__Clear_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Collections_DictionaryBase_void__CopyTo_0__2__Array_i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL array, int32_t index);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_DictionaryBase_IDictionaryEnumerator__GetEnumerator_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_DictionaryBase_i32__get_Count_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_DictionaryBase_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Collections_Queue_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Queue_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Queue_ctor_0__1__ICollection)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL col);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Queue_ctor_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t capacity);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Queue_ctor_0__2__i32_f32)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t capacity, float growFactor);
    void (* _Nonnull  _fp_System_Collections_Queue_void__Clear_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Queue_Object__Clone_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_Queue_bool__Contains_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE obj);
    void (* _Nonnull  _fp_System_Collections_Queue_void__CopyTo_0__2__Array_i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL array, int32_t index);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Collections_Queue_Object__Dequeue_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Collections_Queue_void__Enqueue_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE obj);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Queue_IEnumerator__GetEnumerator_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Collections_Queue_Object__Peek_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Queue_Queue__Synchronized_0__1__Queue)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL queue);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Queue_ObjectArray__ToArray_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Collections_Queue_void__TrimToSize_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_Queue_i32__get_Count_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_Queue_bool__get_IsSynchronized_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Queue_Object__get_SyncRoot_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Queue_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Collections_ReadOnlyCollectionBase_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_ReadOnlyCollectionBase_IEnumerator__GetEnumerator_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_ReadOnlyCollectionBase_i32__get_Count_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_ReadOnlyCollectionBase_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Collections_SortedList_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_ctor_0__1__IComparer)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE comparer);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_ctor_0__2__IComparer_i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE comparer, int32_t capacity);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_ctor_0__1__IDictionary)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL d);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_ctor_0__2__IDictionary_IComparer)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL d, SG_HNDL_NULLABLE comparer);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_ctor_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialCapacity);
    void (* _Nonnull  _fp_System_Collections_SortedList_void__Add_0__2__Object_Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key, SG_HNDL_NULLABLE value);
    void (* _Nonnull  _fp_System_Collections_SortedList_void__Clear_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_Object__Clone_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_SortedList_bool__Contains_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key);
    int32_t (* _Nonnull  _fp_System_Collections_SortedList_bool__ContainsKey_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key);
    int32_t (* _Nonnull  _fp_System_Collections_SortedList_bool__ContainsValue_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value);
    void (* _Nonnull  _fp_System_Collections_SortedList_void__CopyTo_0__2__Array_i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL array, int32_t arrayIndex);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Collections_SortedList_Object__GetByIndex_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t index);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_IDictionaryEnumerator__GetEnumerator_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_Object__GetKey_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t index);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_IList__GetKeyList_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_IList__GetValueList_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_SortedList_i32__IndexOfKey_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key);
    int32_t (* _Nonnull  _fp_System_Collections_SortedList_i32__IndexOfValue_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value);
    void (* _Nonnull  _fp_System_Collections_SortedList_void__Remove_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key);
    void (* _Nonnull  _fp_System_Collections_SortedList_void__RemoveAt_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t index);
    void (* _Nonnull  _fp_System_Collections_SortedList_void__SetByIndex_0__2__i32_Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t index, SG_HNDL_NULLABLE value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_SortedList__Synchronized_0__1__SortedList)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL list);
    void (* _Nonnull  _fp_System_Collections_SortedList_void__TrimToSize_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_SortedList_i32__get_Capacity_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Collections_SortedList_void__set_Capacity_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    int32_t (* _Nonnull  _fp_System_Collections_SortedList_i32__get_Count_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_SortedList_bool__get_IsFixedSize_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_SortedList_bool__get_IsReadOnly_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_SortedList_bool__get_IsSynchronized_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_ICollection__get_Keys_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_Object__get_SyncRoot_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_ICollection__get_Values_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Collections_SortedList_Object__get_Item_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key);
    void (* _Nonnull  _fp_System_Collections_SortedList_void__set_Item_0__2__Object_Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key, SG_HNDL_NULLABLE value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_SortedList_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Collections_Stack_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Stack_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Stack_ctor_0__1__ICollection)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL col);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Stack_ctor_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialCapacity);
    void (* _Nonnull  _fp_System_Collections_Stack_void__Clear_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Stack_Object__Clone_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_Stack_bool__Contains_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE obj);
    void (* _Nonnull  _fp_System_Collections_Stack_void__CopyTo_0__2__Array_i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL array, int32_t index);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Stack_IEnumerator__GetEnumerator_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Collections_Stack_Object__Peek_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_System_Collections_Stack_Object__Pop_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_System_Collections_Stack_void__Push_0__1__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE obj);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Stack_Stack__Synchronized_0__1__Stack)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL stack);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Stack_ObjectArray__ToArray_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_Stack_i32__get_Count_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_System_Collections_Stack_bool__get_IsSynchronized_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Stack_Object__get_SyncRoot_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Stack_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_System_Collections_Specialized_CollectionsUtil_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Specialized_CollectionsUtil_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__1__IDictionary)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL d);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t capacity);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Specialized_CollectionsUtil_SortedList__CreateCaseInsensitiveSortedList_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NONNULL (* _Nonnull  _fp_System_Collections_Specialized_CollectionsUtil_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
} _g_System_Collections_NonGeneric;

static void my_init() {
    _sg_resolve_jumptable("System_Collections_NonGeneric", 29, &_g_System_Collections_NonGeneric);
}

TYP System_Collections_CaseInsensitiveComparer_get_type_handle(void) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Collections_CaseInsensitiveComparer_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_CaseInsensitiveComparer_ctor_0__1__CultureInfo(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL culture) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_ctor_0__1__CultureInfo) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_ctor_0__1__CultureInfo(__thrown, culture);
    return ret;
}

int32_t System_Collections_CaseInsensitiveComparer_i32__Compare_0__2__Object_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE a, SG_HNDL_NULLABLE b) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_i32__Compare_0__2__Object_Object) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_i32__Compare_0__2__Object_Object(__thrown, __self_h, a, b);
    return ret;
}

SG_HNDL_NONNULL System_Collections_CaseInsensitiveComparer_CaseInsensitiveComparer__get_Default_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_CaseInsensitiveComparer__get_Default_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_CaseInsensitiveComparer__get_Default_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_CaseInsensitiveComparer_CaseInsensitiveComparer__get_DefaultInvariant_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_CaseInsensitiveComparer__get_DefaultInvariant_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_CaseInsensitiveComparer__get_DefaultInvariant_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_CaseInsensitiveComparer_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveComparer_cast(__thrown, __h);
    return ret;
}

TYP System_Collections_CaseInsensitiveHashCodeProvider_get_type_handle(void) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Collections_CaseInsensitiveHashCodeProvider_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_CaseInsensitiveHashCodeProvider_ctor_0__1__CultureInfo(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL culture) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_ctor_0__1__CultureInfo) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_ctor_0__1__CultureInfo(__thrown, culture);
    return ret;
}

int32_t System_Collections_CaseInsensitiveHashCodeProvider_i32__GetHashCode_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL obj) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_i32__GetHashCode_0__1__Object) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_i32__GetHashCode_0__1__Object(__thrown, __self_h, obj);
    return ret;
}

SG_HNDL_NONNULL System_Collections_CaseInsensitiveHashCodeProvider_CaseInsensitiveHashCodeProvider__get_Default_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_CaseInsensitiveHashCodeProvider__get_Default_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_CaseInsensitiveHashCodeProvider__get_Default_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_CaseInsensitiveHashCodeProvider_CaseInsensitiveHashCodeProvider__get_DefaultInvariant_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_CaseInsensitiveHashCodeProvider__get_DefaultInvariant_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_CaseInsensitiveHashCodeProvider__get_DefaultInvariant_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_CaseInsensitiveHashCodeProvider_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CaseInsensitiveHashCodeProvider_cast(__thrown, __h);
    return ret;
}

TYP System_Collections_CollectionBase_get_type_handle(void) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_get_type_handle();
    return ret;
}

void System_Collections_CollectionBase_void__Clear_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_void__Clear_0__0) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_void__Clear_0__0(__thrown, __self_h);
}

SG_HNDL_NONNULL System_Collections_CollectionBase_IEnumerator__GetEnumerator_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_IEnumerator__GetEnumerator_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_IEnumerator__GetEnumerator_0__0(__thrown, __self_h);
    return ret;
}

void System_Collections_CollectionBase_void__RemoveAt_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t index) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_void__RemoveAt_0__1__i32) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_void__RemoveAt_0__1__i32(__thrown, __self_h, index);
}

int32_t System_Collections_CollectionBase_i32__get_Capacity_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_i32__get_Capacity_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_i32__get_Capacity_0__0(__thrown, __self_h);
    return ret;
}

void System_Collections_CollectionBase_void__set_Capacity_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_void__set_Capacity_0__1__i32) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_void__set_Capacity_0__1__i32(__thrown, __self_h, value);
}

int32_t System_Collections_CollectionBase_i32__get_Count_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_i32__get_Count_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_i32__get_Count_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_CollectionBase_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_CollectionBase_cast(__thrown, __h);
    return ret;
}

TYP System_Collections_DictionaryBase_get_type_handle(void) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_get_type_handle();
    return ret;
}

void System_Collections_DictionaryBase_void__Clear_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_void__Clear_0__0) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_void__Clear_0__0(__thrown, __self_h);
}

void System_Collections_DictionaryBase_void__CopyTo_0__2__Array_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL array, int32_t index) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_void__CopyTo_0__2__Array_i32) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_void__CopyTo_0__2__Array_i32(__thrown, __self_h, array, index);
}

SG_HNDL_NONNULL System_Collections_DictionaryBase_IDictionaryEnumerator__GetEnumerator_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_IDictionaryEnumerator__GetEnumerator_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_IDictionaryEnumerator__GetEnumerator_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_DictionaryBase_i32__get_Count_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_i32__get_Count_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_i32__get_Count_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_DictionaryBase_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_DictionaryBase_cast(__thrown, __h);
    return ret;
}

TYP System_Collections_Queue_get_type_handle(void) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Collections_Queue_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Queue_ctor_0__1__ICollection(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL col) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_ctor_0__1__ICollection) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_ctor_0__1__ICollection(__thrown, col);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Queue_ctor_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t capacity) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_ctor_0__1__i32) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_ctor_0__1__i32(__thrown, capacity);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Queue_ctor_0__2__i32_f32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t capacity, float growFactor) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_ctor_0__2__i32_f32) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_ctor_0__2__i32_f32(__thrown, capacity, growFactor);
    return ret;
}

void System_Collections_Queue_void__Clear_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_void__Clear_0__0) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_Queue_void__Clear_0__0(__thrown, __self_h);
}

SG_HNDL_NONNULL System_Collections_Queue_Object__Clone_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_Object__Clone_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_Object__Clone_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_Queue_bool__Contains_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE obj) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_bool__Contains_0__1__Object) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_bool__Contains_0__1__Object(__thrown, __self_h, obj);
    return ret;
}

void System_Collections_Queue_void__CopyTo_0__2__Array_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL array, int32_t index) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_void__CopyTo_0__2__Array_i32) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_Queue_void__CopyTo_0__2__Array_i32(__thrown, __self_h, array, index);
}

SG_HNDL_NULLABLE System_Collections_Queue_Object__Dequeue_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_Object__Dequeue_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_Object__Dequeue_0__0(__thrown, __self_h);
    return ret;
}

void System_Collections_Queue_void__Enqueue_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE obj) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_void__Enqueue_0__1__Object) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_Queue_void__Enqueue_0__1__Object(__thrown, __self_h, obj);
}

SG_HNDL_NONNULL System_Collections_Queue_IEnumerator__GetEnumerator_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_IEnumerator__GetEnumerator_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_IEnumerator__GetEnumerator_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Collections_Queue_Object__Peek_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_Object__Peek_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_Object__Peek_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Queue_Queue__Synchronized_0__1__Queue(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL queue) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_Queue__Synchronized_0__1__Queue) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_Queue__Synchronized_0__1__Queue(__thrown, queue);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Queue_ObjectArray__ToArray_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_ObjectArray__ToArray_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_ObjectArray__ToArray_0__0(__thrown, __self_h);
    return ret;
}

void System_Collections_Queue_void__TrimToSize_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_void__TrimToSize_0__0) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_Queue_void__TrimToSize_0__0(__thrown, __self_h);
}

int32_t System_Collections_Queue_i32__get_Count_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_i32__get_Count_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_i32__get_Count_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_Queue_bool__get_IsSynchronized_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_bool__get_IsSynchronized_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_bool__get_IsSynchronized_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Queue_Object__get_SyncRoot_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_Object__get_SyncRoot_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_Object__get_SyncRoot_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Queue_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Queue_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Queue_cast(__thrown, __h);
    return ret;
}

TYP System_Collections_ReadOnlyCollectionBase_get_type_handle(void) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_ReadOnlyCollectionBase_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Collections_NonGeneric._fp_System_Collections_ReadOnlyCollectionBase_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Collections_ReadOnlyCollectionBase_IEnumerator__GetEnumerator_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_ReadOnlyCollectionBase_IEnumerator__GetEnumerator_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_ReadOnlyCollectionBase_IEnumerator__GetEnumerator_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_ReadOnlyCollectionBase_i32__get_Count_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_ReadOnlyCollectionBase_i32__get_Count_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_ReadOnlyCollectionBase_i32__get_Count_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_ReadOnlyCollectionBase_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_ReadOnlyCollectionBase_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_ReadOnlyCollectionBase_cast(__thrown, __h);
    return ret;
}

TYP System_Collections_SortedList_get_type_handle(void) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_ctor_0__1__IComparer(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE comparer) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__1__IComparer) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__1__IComparer(__thrown, comparer);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_ctor_0__2__IComparer_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE comparer, int32_t capacity) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__2__IComparer_i32) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__2__IComparer_i32(__thrown, comparer, capacity);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_ctor_0__1__IDictionary(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL d) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__1__IDictionary) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__1__IDictionary(__thrown, d);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_ctor_0__2__IDictionary_IComparer(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL d, SG_HNDL_NULLABLE comparer) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__2__IDictionary_IComparer) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__2__IDictionary_IComparer(__thrown, d, comparer);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_ctor_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialCapacity) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__1__i32) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ctor_0__1__i32(__thrown, initialCapacity);
    return ret;
}

void System_Collections_SortedList_void__Add_0__2__Object_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key, SG_HNDL_NULLABLE value) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__Add_0__2__Object_Object) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__Add_0__2__Object_Object(__thrown, __self_h, key, value);
}

void System_Collections_SortedList_void__Clear_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__Clear_0__0) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__Clear_0__0(__thrown, __self_h);
}

SG_HNDL_NONNULL System_Collections_SortedList_Object__Clone_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_Object__Clone_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_Object__Clone_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_SortedList_bool__Contains_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__Contains_0__1__Object) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__Contains_0__1__Object(__thrown, __self_h, key);
    return ret;
}

int32_t System_Collections_SortedList_bool__ContainsKey_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__ContainsKey_0__1__Object) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__ContainsKey_0__1__Object(__thrown, __self_h, key);
    return ret;
}

int32_t System_Collections_SortedList_bool__ContainsValue_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__ContainsValue_0__1__Object) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__ContainsValue_0__1__Object(__thrown, __self_h, value);
    return ret;
}

void System_Collections_SortedList_void__CopyTo_0__2__Array_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL array, int32_t arrayIndex) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__CopyTo_0__2__Array_i32) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__CopyTo_0__2__Array_i32(__thrown, __self_h, array, arrayIndex);
}

SG_HNDL_NULLABLE System_Collections_SortedList_Object__GetByIndex_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t index) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_Object__GetByIndex_0__1__i32) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_Object__GetByIndex_0__1__i32(__thrown, __self_h, index);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_IDictionaryEnumerator__GetEnumerator_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_IDictionaryEnumerator__GetEnumerator_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_IDictionaryEnumerator__GetEnumerator_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_Object__GetKey_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t index) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_Object__GetKey_0__1__i32) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_Object__GetKey_0__1__i32(__thrown, __self_h, index);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_IList__GetKeyList_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_IList__GetKeyList_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_IList__GetKeyList_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_IList__GetValueList_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_IList__GetValueList_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_IList__GetValueList_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_SortedList_i32__IndexOfKey_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_i32__IndexOfKey_0__1__Object) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_i32__IndexOfKey_0__1__Object(__thrown, __self_h, key);
    return ret;
}

int32_t System_Collections_SortedList_i32__IndexOfValue_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_i32__IndexOfValue_0__1__Object) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_i32__IndexOfValue_0__1__Object(__thrown, __self_h, value);
    return ret;
}

void System_Collections_SortedList_void__Remove_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__Remove_0__1__Object) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__Remove_0__1__Object(__thrown, __self_h, key);
}

void System_Collections_SortedList_void__RemoveAt_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t index) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__RemoveAt_0__1__i32) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__RemoveAt_0__1__i32(__thrown, __self_h, index);
}

void System_Collections_SortedList_void__SetByIndex_0__2__i32_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t index, SG_HNDL_NULLABLE value) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__SetByIndex_0__2__i32_Object) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__SetByIndex_0__2__i32_Object(__thrown, __self_h, index, value);
}

SG_HNDL_NONNULL System_Collections_SortedList_SortedList__Synchronized_0__1__SortedList(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL list) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_SortedList__Synchronized_0__1__SortedList) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_SortedList__Synchronized_0__1__SortedList(__thrown, list);
    return ret;
}

void System_Collections_SortedList_void__TrimToSize_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__TrimToSize_0__0) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__TrimToSize_0__0(__thrown, __self_h);
}

int32_t System_Collections_SortedList_i32__get_Capacity_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_i32__get_Capacity_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_i32__get_Capacity_0__0(__thrown, __self_h);
    return ret;
}

void System_Collections_SortedList_void__set_Capacity_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__set_Capacity_0__1__i32) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__set_Capacity_0__1__i32(__thrown, __self_h, value);
}

int32_t System_Collections_SortedList_i32__get_Count_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_i32__get_Count_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_i32__get_Count_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_SortedList_bool__get_IsFixedSize_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__get_IsFixedSize_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__get_IsFixedSize_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_SortedList_bool__get_IsReadOnly_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__get_IsReadOnly_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__get_IsReadOnly_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_SortedList_bool__get_IsSynchronized_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__get_IsSynchronized_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_bool__get_IsSynchronized_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_ICollection__get_Keys_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ICollection__get_Keys_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ICollection__get_Keys_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_Object__get_SyncRoot_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_Object__get_SyncRoot_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_Object__get_SyncRoot_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_SortedList_ICollection__get_Values_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ICollection__get_Values_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_ICollection__get_Values_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Collections_SortedList_Object__get_Item_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_Object__get_Item_0__1__Object) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_Object__get_Item_0__1__Object(__thrown, __self_h, key);
    return ret;
}

void System_Collections_SortedList_void__set_Item_0__2__Object_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL key, SG_HNDL_NULLABLE value) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__set_Item_0__2__Object_Object) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_void__set_Item_0__2__Object_Object(__thrown, __self_h, key, value);
}

SG_HNDL_NONNULL System_Collections_SortedList_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_SortedList_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_SortedList_cast(__thrown, __h);
    return ret;
}

TYP System_Collections_Stack_get_type_handle(void) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Collections_Stack_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Stack_ctor_0__1__ICollection(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL col) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_ctor_0__1__ICollection) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_ctor_0__1__ICollection(__thrown, col);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Stack_ctor_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t initialCapacity) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_ctor_0__1__i32) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_ctor_0__1__i32(__thrown, initialCapacity);
    return ret;
}

void System_Collections_Stack_void__Clear_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_void__Clear_0__0) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_Stack_void__Clear_0__0(__thrown, __self_h);
}

SG_HNDL_NONNULL System_Collections_Stack_Object__Clone_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_Object__Clone_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_Object__Clone_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_Stack_bool__Contains_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE obj) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_bool__Contains_0__1__Object) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_bool__Contains_0__1__Object(__thrown, __self_h, obj);
    return ret;
}

void System_Collections_Stack_void__CopyTo_0__2__Array_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL array, int32_t index) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_void__CopyTo_0__2__Array_i32) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_Stack_void__CopyTo_0__2__Array_i32(__thrown, __self_h, array, index);
}

SG_HNDL_NONNULL System_Collections_Stack_IEnumerator__GetEnumerator_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_IEnumerator__GetEnumerator_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_IEnumerator__GetEnumerator_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Collections_Stack_Object__Peek_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_Object__Peek_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_Object__Peek_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE System_Collections_Stack_Object__Pop_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_Object__Pop_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_Object__Pop_0__0(__thrown, __self_h);
    return ret;
}

void System_Collections_Stack_void__Push_0__1__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE obj) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_void__Push_0__1__Object) {
        my_init();
    }
    _g_System_Collections_NonGeneric._fp_System_Collections_Stack_void__Push_0__1__Object(__thrown, __self_h, obj);
}

SG_HNDL_NONNULL System_Collections_Stack_Stack__Synchronized_0__1__Stack(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL stack) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_Stack__Synchronized_0__1__Stack) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_Stack__Synchronized_0__1__Stack(__thrown, stack);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Stack_ObjectArray__ToArray_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_ObjectArray__ToArray_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_ObjectArray__ToArray_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_Stack_i32__get_Count_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_i32__get_Count_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_i32__get_Count_0__0(__thrown, __self_h);
    return ret;
}

int32_t System_Collections_Stack_bool__get_IsSynchronized_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_bool__get_IsSynchronized_0__0) {
        my_init();
    }
    int32_t ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_bool__get_IsSynchronized_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Stack_Object__get_SyncRoot_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_Object__get_SyncRoot_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_Object__get_SyncRoot_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Stack_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Stack_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Stack_cast(__thrown, __h);
    return ret;
}

TYP System_Collections_Specialized_CollectionsUtil_get_type_handle(void) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_get_type_handle) {
        my_init();
    }
    TYP ret = _g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL System_Collections_Specialized_CollectionsUtil_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__1__IDictionary(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL d) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__1__IDictionary) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__1__IDictionary(__thrown, d);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, int32_t capacity) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__1__i32) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_Hashtable__CreateCaseInsensitiveHashtable_0__1__i32(__thrown, capacity);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Specialized_CollectionsUtil_SortedList__CreateCaseInsensitiveSortedList_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_SortedList__CreateCaseInsensitiveSortedList_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_SortedList__CreateCaseInsensitiveSortedList_0__0(__thrown);
    return ret;
}

SG_HNDL_NONNULL System_Collections_Specialized_CollectionsUtil_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_System_Collections_NonGeneric._fp_System_Collections_Specialized_CollectionsUtil_cast(__thrown, __h);
    return ret;
}

