// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "System_Windows.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
} _g_System_Windows;

static void my_init() {
    _sg_resolve_jumptable("System_Windows", 14, &_g_System_Windows);
}

