// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "System_Threading_Tasks.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
} _g_System_Threading_Tasks;

static void my_init() {
    _sg_resolve_jumptable("System_Threading_Tasks", 22, &_g_System_Threading_Tasks);
}

