// Copyright 2021 SourceGear

import jumptable_dotnet;

extension dotnet.System.String {
#if not
    public static func == (left : dotnet.System.String, right : Swift.String) throws -> Bool {
        let s_right = dotnet.System.String(swiftString: right);
        return try left.Equals(s_right);
    }
#endif

    // TODO seems like this should be generated by bindgen from the op_Eq or whatever
    public static func == (left : dotnet.System.String, right : dotnet.System.String) throws -> Bool {
        return try left.Equals(value: right);
    }

}

